import Foundation

enum Localization {
    private static let translations: [String: [String: String]] = [

    // MARK: - Common / General
    "Dashboard": ["pt-BR": "Painel"],
    "Schedule": ["pt-BR": "Agenda"],
    "Clients": ["pt-BR": "Clientes"],
    "Finances": ["pt-BR": "Financeiro"],
    "Business": ["pt-BR": "Negócio"],
    "Operational Overview": ["pt-BR": "Visão Operacional"],
    "Settings": ["pt-BR": "Configurações"],
    "Close": ["pt-BR": "Fechar"],
    "Save": ["pt-BR": "Salvar"],
    "Cancel": ["pt-BR": "Cancelar"],
    "Done": ["pt-BR": "Concluído"],
    "Delete": ["pt-BR": "Excluir"],
    "Edit": ["pt-BR": "Editar"],
    "Add": ["pt-BR": "Adicionar"],
    "View all": ["pt-BR": "Ver tudo"],
    "Loading...": ["pt-BR": "Carregando..."],
    "Error": ["pt-BR": "Erro"],
    "Success": ["pt-BR": "Sucesso"],
    "Overview": ["pt-BR": "Visão Geral"],
    "Activity": ["pt-BR": "Atividade"],
    "Crew Breakdown": ["pt-BR": "Resumo da Equipe"],
    "Jobs Assigned": ["pt-BR": "Serviços Atribuídos"],
    "Completion": ["pt-BR": "Conclusão"],
    "Cleaners": ["pt-BR": "Limpadores"],
    "Team Status": ["pt-BR": "Status da Equipe"],
    "DEVICE CONTROL": ["pt-BR": "CONTROLE DO DISPOSITIVO"],
    "Tune how Sweeply behaves on this device.": ["pt-BR": "Ajuste como o Sweeply se comporta neste dispositivo."],
    "On": ["pt-BR": "Ligado"],
    "Off": ["pt-BR": "Desligado"],
    "Signed out": ["pt-BR": "Deslogado"],
    "Calendar": ["pt-BR": "Calendário"],
    "ACCOUNT CENTER": ["pt-BR": "CENTRO DA CONTA"],
    "Manage your workspace, recovery tools, and account actions.": ["pt-BR": "Gerencie seu espaço de trabalho, ferramentas de recuperação e ações da conta."],
    "Workspace": ["pt-BR": "Espaço de Trabalho"],
    "Own business": ["pt-BR": "Empresa própria"],
    "Mode": ["pt-BR": "Modo"],
    "Teams": ["pt-BR": "Equipes"],
    "Account Identity": ["pt-BR": "Identidade da Conta"],
    "Your account": ["pt-BR": "Sua conta"],
    "No business name yet": ["pt-BR": "Ainda sem nome da empresa"],
    "No email saved": ["pt-BR": "Nenhum e-mail salvo"],
    "Workspaces": ["pt-BR": "Espaços de Trabalho"],
    "Switch between your business and any active team memberships.": ["pt-BR": "Alterne entre sua empresa e qualquer equipe ativa."],
    "No additional workspaces yet.": ["pt-BR": "Ainda sem espaços de trabalho adicionais."],
    "When you join a team, it appears here for one-tap switching.": ["pt-BR": "Quando você entrar em uma equipe, ela aparecerá aqui para alternância com um toque."],
    "Return to Own Business": ["pt-BR": "Voltar para a Própria Empresa"],
    "Switch back to your main workspace.": ["pt-BR": "Volte para seu espaço principal."],
    "Recovery & Setup": ["pt-BR": "Recuperação e Configuração"],
    "Revisit onboarding or reset your password when needed.": ["pt-BR": "Revise a introdução ou redefina sua senha quando necessário."],
    "Replay App Intro": ["pt-BR": "Rever Introdução do App"],
    "Review the onboarding experience again.": ["pt-BR": "Revise a experiência de onboarding novamente."],
    "Replay Business Setup": ["pt-BR": "Rever Configuração da Empresa"],
    "Reopen the business setup flow.": ["pt-BR": "Reabra o fluxo de configuração da empresa."],
    "Open": ["pt-BR": "Abrir"],
    "Send a reset email to your account inbox.": ["pt-BR": "Envie um e-mail de redefinição para a caixa de entrada da sua conta."],
    "Danger Zone": ["pt-BR": "Zona de Risco"],
    "Delete the account only when you are sure the data can go.": ["pt-BR": "Exclua a conta somente quando tiver certeza de que os dados podem ir embora."],
    "This permanently removes your account and all business data from Sweeply.": ["pt-BR": "Isso remove permanentemente sua conta e todos os dados da empresa do Sweeply."],
    "Security & Sync": ["pt-BR": "Segurança e Sincronização"],
    "Protect access and keep jobs flowing into Calendar.": ["pt-BR": "Proteja o acesso e mantenha os serviços indo para o Calendário."],
    "Enabled for job reminders and alerts.": ["pt-BR": "Ativado para lembretes e alertas de serviços."],
    "Enable to receive job and invoice reminders.": ["pt-BR": "Ative para receber lembretes de serviços e faturas."],
    "Preview how reminders appear on the device.": ["pt-BR": "Veja como os lembretes aparecem no dispositivo."],
    "Switch the app language instantly.": ["pt-BR": "Alterne o idioma do app instantaneamente."],
    "Português and English are available across the app.": ["pt-BR": "Português e inglês estão disponíveis em todo o app."],
    "Value": ["pt-BR": "Valor"],
    "Week": ["pt-BR": "Semana"],
    "Now": ["pt-BR": "Agora"],
    "Pay": ["pt-BR": "Pagamento"],

    // MARK: - Dashboard
    "Good morning": ["pt-BR": "Bom dia"],
    "Good afternoon": ["pt-BR": "Boa tarde"],
    "Good evening": ["pt-BR": "Boa noite"],
    "Total Clients": ["pt-BR": "Total de Clientes"],
    "Upcoming Jobs": ["pt-BR": "Próximos Serviços"],
    "Revenue": ["pt-BR": "Faturamento"],
    "Outstanding": ["pt-BR": "Pendente"],
    "Completed": ["pt-BR": "Concluídos"],
    "Remaining": ["pt-BR": "Restantes"],
    "Week Earned": ["pt-BR": "Ganho na Semana"],
    "Today's Schedule": ["pt-BR": "Agenda de Hoje"],
    "No jobs scheduled for today": ["pt-BR": "Nenhum serviço agendado para hoje"],
    "Business Health": ["pt-BR": "Saúde do Negócio"],
    "Job Value": ["pt-BR": "Valor dos Serviços"],
    "Total value of this week's jobs": ["pt-BR": "Valor total dos serviços da semana"],
    "Visits Scheduled": ["pt-BR": "Visitas Agendadas"],
    "Outstanding Invoices": ["pt-BR": "Faturas Pendentes"],
"All caught up — no outstanding invoices": ["pt-BR": "Tudo em dia — sem faturas pendentes"],
    "Mark Paid": ["pt-BR": "Marcar Pago"],
    "Avg Job Value": ["pt-BR": "Valor Médio do Serviço"],
    "Weekly Jobs": ["pt-BR": "Serviços da Semana"],
    "Jobs done this week": ["pt-BR": "Serviços feitos esta semana"],
    "Earned This Month": ["pt-BR": "Ganho Este Mês"],
    "Collected All-Time": ["pt-BR": "Coletado no Total"],
    "Active This Month": ["pt-BR": "Ativo Este Mês"],
    "Upcoming jobs": ["pt-BR": "Serviços futuros"],
    "No upcoming jobs": ["pt-BR": "Nenhum serviço próximo"],
    "Most requested services this month": ["pt-BR": "Serviços mais pedidos este mês"],
    "Highest activity this month": ["pt-BR": "Maior atividade este mês"],
    "How the operation is moving this month": ["pt-BR": "Como a operação está este mês"],
    "Your nearest scheduled visit": ["pt-BR": "Sua próxima visita agendada"],
    "Next Up": ["pt-BR": "Próximo"],
    "Completed Jobs": ["pt-BR": "Serviços Concluídos"],
    "Services": ["pt-BR": "Serviços"],
    "Extras": ["pt-BR": "Extras"],
    "Role": ["pt-BR": "Cargo"],
    "First Name *": ["pt-BR": "Nome *"],
    "Last Name": ["pt-BR": "Sobrenome"],
    "Street Address": ["pt-BR": "Endereço"],
    "Street": ["pt-BR": "Rua"],
    "Entry Instructions": ["pt-BR": "Instruções de Acesso"],
    "Assigned": ["pt-BR": "Atribuídos"],
    "Upcoming": ["pt-BR": "Próximos"],
    "Earned": ["pt-BR": "Ganho"],
    "Total": ["pt-BR": "Total"],
    "Active": ["pt-BR": "Ativo"],
    "Invited": ["pt-BR": "Convidado"],
    "Inactive": ["pt-BR": "Inativo"],
    "Jobs scheduled for the next 7 days": ["pt-BR": "Serviços agendados para os próximos 7 dias"],
    "This Month": ["pt-BR": "Este Mês"],
    "Job Started": ["pt-BR": "Serviço Iniciado"],
    "Job Completed": ["pt-BR": "Serviço Concluído"],
    "Job Cancelled": ["pt-BR": "Serviço Cancelado"],
    "Jobs Done": ["pt-BR": "Serviços Feitos"],
    "Revenue Milestone": ["pt-BR": "Meta de Faturamento"],
    "Revenue Milestone Reached 🎉": ["pt-BR": "Meta de Faturamento Atingida 🎉"],
    "Done Wk": ["pt-BR": "Feito Sem"],
    "In Prog.": ["pt-BR": "Em And."],
    "Mark Complete": ["pt-BR": "Marcar Concluído"],
    "View Job": ["pt-BR": "Ver Serviço"],
    "Revenue Milestone 🎉": ["pt-BR": "Meta de Faturamento 🎉"],
    "DAILY PAY": ["pt-BR": "PAGAMENTO DIÁRIO"],
    "It's Pay Day!": ["pt-BR": "É Dia de Pagamento!"],
    "Gross Earned": ["pt-BR": "Total Ganho"],
    "Avg / Job": ["pt-BR": "Média / Serviço"],
    "Payment History": ["pt-BR": "Histórico de Pagamentos"],
    "Received payments": ["pt-BR": "Pagamentos recebidos"],
    "Avg/Job": ["pt-BR": "Média/Serviço"],
    "In Progress": ["pt-BR": "Em Andamento"],
    "Overdue": ["pt-BR": "Vencido"],
    "Net Profit": ["pt-BR": "Lucro Líquido"],
    "avg. invoice": ["pt-BR": "fatura média"],
    "Collection": ["pt-BR": "Cobrança"],
    "Invoices": ["pt-BR": "Faturas"],
    "Jobs": ["pt-BR": "Serviços"],
    "Scheduled": ["pt-BR": "Agendado"],
    "Coming up": ["pt-BR": "Próximos"],
    "Clear schedule": ["pt-BR": "Agenda livre"],
    "Expenses": ["pt-BR": "Despesas"],
    "Collected": ["pt-BR": "Coletado"],
    "Scheduled jobs": ["pt-BR": "Serviços agendados"],
    "Average Ticket": ["pt-BR": "Ticket Médio"],
    "Recurring Jobs": ["pt-BR": "Serviços Recorrentes"],
    "Duration": ["pt-BR": "Duração"],
    "EARNINGS": ["pt-BR": "GANHOS"],
    "Finance": ["pt-BR": "Financeiro"],
    "Name": ["pt-BR": "Nome"],
    "Email": ["pt-BR": "E-mail"],
    "Phone": ["pt-BR": "Telefone"],
    
    // MARK: - Cleaner specific
    "All Time": ["pt-BR": "Todo Período"],

    // MARK: - Settings
    "Profile": ["pt-BR": "Perfil"],
    "Preferences": ["pt-BR": "Preferências"],
    "Account": ["pt-BR": "Conta"],
    "Push Notifications": ["pt-BR": "Notificações Push"],
    "Job reminders, invoice alerts": ["pt-BR": "Lembretes de serviços, alertas de faturas"],
    "Require Face ID": ["pt-BR": "Exigir Face ID"],
    "Locks app when it goes to background": ["pt-BR": "Bloqueia app quando vai para segundo plano"],
    "Sync Jobs to Calendar": ["pt-BR": "Sincronizar Serviços com Calendário"],
    "Adds scheduled jobs to your Calendar app": ["pt-BR": "Adiciona serviços agendados ao seu aplicativo Calendário"],
    "Sweeply job": ["pt-BR": "Serviço Sweeply"],
    "Last paid %@": ["pt-BR": "Último pagamento %@"],
    "Reset Password": ["pt-BR": "Redefinir Senha"],
    // MARK: - New onboarding flow
    "Log In": ["pt-BR": "Entrar"],
    "Sign Up": ["pt-BR": "Cadastrar"],
    "Back": ["pt-BR": "Voltar"],
    "What best\ndescribes you?": ["pt-BR": "O que melhor\nte descreve?"],
    "Starting a new cleaning business": ["pt-BR": "Começando um novo negócio de limpeza"],
    "Already running, need better tools": ["pt-BR": "Já estou rodando, preciso de melhores ferramentas"],
    "Managing a team of cleaners": ["pt-BR": "Gerenciando uma equipe de limpeza"],
    "Switching from another app": ["pt-BR": "Migrando de outro aplicativo"],
    "What's your\nmain goal?": ["pt-BR": "Qual é o seu\nprincipal objetivo?"],
    "Stay on top of jobs and schedule": ["pt-BR": "Controlar serviços e agenda"],
    "Get invoices paid faster": ["pt-BR": "Receber faturas mais rápido"],
    "Build a bigger client base": ["pt-BR": "Expandir a base de clientes"],
    "Manage and pay my team": ["pt-BR": "Gerenciar e pagar minha equipe"],
    "How many clients\ndo you have now?": ["pt-BR": "Quantos clientes\nvocê tem agora?"],
    "Just starting — 0 to 5": ["pt-BR": "Começando — 0 a 5"],
    "Growing — 6 to 20": ["pt-BR": "Crescendo — 6 a 20"],
    "Established — 21 to 50": ["pt-BR": "Estabelecido — 21 a 50"],
    "Scaling fast — 50+": ["pt-BR": "Escalando — 50+"],
    "Who are your regulars?": ["pt-BR": "Quem são seus clientes fixos?"],
    "We'll add them to your client list.": ["pt-BR": "Vamos adicioná-los à sua lista de clientes."],
    "Add another client": ["pt-BR": "Adicionar outro cliente"],
    "Client name": ["pt-BR": "Nome do cliente"],
    "What's your\nname?": ["pt-BR": "Qual é o\nseu nome?"],
    "This appears on your invoices and client messages.": ["pt-BR": "Isso aparece nas suas faturas e mensagens para clientes."],
    "First name": ["pt-BR": "Nome"],
    "Last name": ["pt-BR": "Sobrenome"],
    "Name your\nbusiness": ["pt-BR": "Nome do\nseu negócio"],
    "You can change this anytime in Settings.": ["pt-BR": "Você pode alterar isso a qualquer momento nas Configurações."],
    "What's your\nemail?": ["pt-BR": "Qual é o\nseu e-mail?"],
    "Enable Passcode": ["pt-BR": "Ativar Senha de Acesso"],
    "Sign in with Face ID instead of a password": ["pt-BR": "Entre com Face ID em vez de senha"],
    "I agree to Sweeply's": ["pt-BR": "Concordo com os"],
    "and": ["pt-BR": "e"],
    "Create a\npassword": ["pt-BR": "Crie uma\nsenha"],
    "Password": ["pt-BR": "Senha"],
    "At least 8 characters": ["pt-BR": "Pelo menos 8 caracteres"],
    "1 uppercase letter": ["pt-BR": "1 letra maiúscula"],
    "1 lowercase letter": ["pt-BR": "1 letra minúscula"],
    "1 number": ["pt-BR": "1 número"],
    "Creating account…": ["pt-BR": "Criando conta…"],

    "Version": ["pt-BR": "Versão"],
    "Build": ["pt-BR": "Build"],
    "Delete Account": ["pt-BR": "Excluir Conta"],
    "Delete your account?": ["pt-BR": "Excluir sua conta?"],
    "This will permanently delete your account and all your business data. This cannot be undone.": ["pt-BR": "Isso excluirá permanentemente sua conta e todos os dados do seu negócio. Esta ação não pode ser desfeita."],
    "Deleting…": ["pt-BR": "Excluindo…"],
    "Business Name": ["pt-BR": "Nome do Negócio"],
    "Business Address": ["pt-BR": "Endereço do Negócio"],
    "Job Defaults": ["pt-BR": "Padrões de Serviço"],
    "Default Hourly Rate": ["pt-BR": "Taxa Horária Padrão"],
    "Default Duration (hrs)": ["pt-BR": "Duração Padrão (hrs)"],
    "Manage Services": ["pt-BR": "Gerenciar Serviços"],
    "Job Extras": ["pt-BR": "Extras de Serviço"],
    "Reminder Timing": ["pt-BR": "Tempo do Lembrete"],
    "1 hr before": ["pt-BR": "1 hora antes"],
    "Morning of": ["pt-BR": "Manhã do dia"],
    "Day before": ["pt-BR": "Dia anterior"],
    "Send Test Notification": ["pt-BR": "Enviar Notificação de Teste"],
    "5s delay": ["pt-BR": "5s de atraso"],
    "Full name is required.": ["pt-BR": "Nome completo é obrigatório."],
    "Business name is required.": ["pt-BR": "Nome do negócio é obrigatório."],
    "Enter a valid email address.": ["pt-BR": "Digite um endereço de e-mail válido."],
    "Enter a valid email address": ["pt-BR": "Digite um endereço de e-mail válido"],
    "First name is required": ["pt-BR": "Nome é obrigatório"],
    "Settings saved.": ["pt-BR": "Configurações salvas."],
    "No authenticated session was found.": ["pt-BR": "Nenhuma sessão autenticada foi encontrada."],
    "Add your email address before requesting a password reset.": ["pt-BR": "Adicione seu endereço de e-mail antes de solicitar redefinição de senha."],
    "Password reset is not available in this mode.": ["pt-BR": "Redefinição de senha não está disponível neste modo."],
    "Password reset email sent to": ["pt-BR": "E-mail de redefinição de senha enviado para"],
    "Failed to save changes.": ["pt-BR": "Falha ao salvar alterações."],
    "Unable to save your settings right now.": ["pt-BR": "Não foi possível salvar suas configurações agora."],
    "Face ID Lock": ["pt-BR": "Bloqueio por Face ID"],
    "Require Face ID when returning to app": ["pt-BR": "Exigir Face ID ao retornar ao app"],
    "Sync to Calendar": ["pt-BR": "Sincronizar com Calendário"],
    "Managed by iOS Settings": ["pt-BR": "Gerenciado pelo iOS"],
    "LANGUAGE": ["pt-BR": "IDIOMA"],
    "SECURITY & SYNC": ["pt-BR": "SEGURANÇA E SINCRONIZAÇÃO"],
    "PERSONAL INFO": ["pt-BR": "INFORMAÇÕES PESSOAIS"],
    "BUSINESS": ["pt-BR": "NEGÓCIO"],
    "NOTIFICATIONS": ["pt-BR": "NOTIFICAÇÕES"],
    "PREFERENCES": ["pt-BR": "PREFERÊNCIAS"],
    "DANGER ZONE": ["pt-BR": "ZONA DE PERIGO"],
    "Switch to My Business": ["pt-BR": "Mudar para Meu Negócio"],
    "Cleaning Business": ["pt-BR": "Negócio de Limpeza"],
    "My Business": ["pt-BR": "Meu Negócio"],
    "Support": ["pt-BR": "Suporte"],
    "Subscription": ["pt-BR": "Assinatura"],
    "Product updates": ["pt-BR": "Novidades do Produto"],
    "Refer a friend": ["pt-BR": "Indicar um Amigo"],
    "About": ["pt-BR": "Sobre"],
    "Company details": ["pt-BR": "Dados da Empresa"],
    "Logout": ["pt-BR": "Sair"],
    "Log out": ["pt-BR": "Sair"],
    "You'll need to sign in again to access your account.": ["pt-BR": "Você precisará fazer login novamente para acessar sua conta."],
    "MY TEAMS": ["pt-BR": "MINHAS EQUIPES"],
    "Re-run App Intro": ["pt-BR": "Revisão da Introdução"],
    "Re-run Business Setup": ["pt-BR": "Revisão Configuração do Negócio"],
    "Showing on your dashboard": ["pt-BR": "Exibindo no seu painel"],
    "APP INFO": ["pt-BR": "INFORMAÇÕES DO APP"],
    "TEAM": ["pt-BR": "EQUIPE"],

    // MARK: - Language
    "Language": ["pt-BR": "Idioma"],
    "App Language": ["pt-BR": "Idioma do App"],
    "Choose your preferred language": ["pt-BR": "Escolha seu idioma preferido"],

    // MARK: - Notifications
    "Notifications": ["pt-BR": "Notificações"],
    "All": ["pt-BR": "Todas"],
    "Unread": ["pt-BR": "Não lidas"],
    "No notifications": ["pt-BR": "Sem notificações"],
    "All caught up": ["pt-BR": "Tudo em dia"],
    "No schedule updates": ["pt-BR": "Sem atualizações de agenda"],
    "No job updates": ["pt-BR": "Sem atualizações de serviços"],
    "No billing activity": ["pt-BR": "Sem atividade de faturamento"],
    "You're up to date. New notifications will appear here.": ["pt-BR": "Você está em dia. Novas notificações aparecerão aqui."],
    "You've read everything. Check back later for updates.": ["pt-BR": "Você leu tudo. Volte mais tarde para atualizações."],
    "No schedule changes or updates at the moment.": ["pt-BR": "Nenhuma mudança ou atualização de agenda no momento."],
    "No job updates at the moment.": ["pt-BR": "Nenhuma atualização de serviço no momento."],
    "No invoice or payment activity to show.": ["pt-BR": "Nenhuma atividade de fatura ou pagamento para mostrar."],
    "Mark read": ["pt-BR": "Marcar como lido"],
    "Mark as Unread": ["pt-BR": "Marcar como não lido"],
    "Mark as Read": ["pt-BR": "Marcar como lido"],
    "Billing": ["pt-BR": "Faturamento"],
    "No team activity": ["pt-BR": "Sem atividade da equipe"],
    "Invite acceptances and team updates will appear here.": ["pt-BR": "Aceitações de convite e atualizações da equipe aparecerão aqui."],
    "Check-ins, completions, and job assignments will appear here.": ["pt-BR": "Check-ins, conclusões e atribuições de serviços aparecerão aqui."],
    "Invoice due dates and payment confirmations will appear here.": ["pt-BR": "Datas de vencimento e confirmações de pagamento aparecerão aqui."],
    "Job in 1 Hour": ["pt-BR": "Serviço em 1 Hora"],
    "Standard Clean at": ["pt-BR": "Limpeza Padrão em"],
    "Invoice Due Soon": ["pt-BR": "Fatura Vencendo em Breve"],
    "is due in %d days": ["pt-BR": "vence em %d dias"],
    "Enabled — job reminders & alerts": ["pt-BR": "Ativado — lembretes de serviços e alertas"],
    "Tap to enable job reminders": ["pt-BR": "Toque para ativar lembretes de serviços"],
    "Job Reminder": ["pt-BR": "Lembrete de Serviço"],
    "Invoice Due": ["pt-BR": "Fatura Vencendo"],
    "Test": ["pt-BR": "Teste"],
    "Standard Clean at Sarah M. — 123 Main St": ["pt-BR": "Limpeza Padrão na Sarah M. — Rua Principal 123"],
    "INV-0042 for Sarah M. is due in 3 days — $320.00": ["pt-BR": "INV-0042 para Sarah M. vence em 3 dias — R$ 320,00"],
    "Test Notification": ["pt-BR": "Notificação de Teste"],
    "Team Invitation": ["pt-BR": "Convite da equipe"],
    "You've been invited to join a team on Sweeply. Open the Team tab to accept.": ["pt-BR": "Você foi convidado para entrar em uma equipe no Sweeply. Abra a aba Equipe para aceitar."],
    "Team Member Joined": ["pt-BR": "Membro da equipe entrou"],
    "%@ accepted your invitation and joined the team": ["pt-BR": "%@ aceitou seu convite e entrou para a equipe"],
    "%@ is now on your team!": ["pt-BR": "%@ agora faz parte da sua equipe!"],
    "%@ accepted your invite and joined the team — you can now assign them jobs.": ["pt-BR": "%@ aceitou seu convite e entrou para a equipe — agora você pode atribuir serviços a essa pessoa."],
    "Payment Received": ["pt-BR": "Pagamento recebido"],
    "You received %@ from %@. Check your Finance tab.": ["pt-BR": "Você recebeu %@ de %@. Confira a aba Financeiro."],
    "your manager": ["pt-BR": "seu gerente"],
    "Your %@ from %@ should be processed today. Check with your manager.": ["pt-BR": "Seu %@ de %@ deve ser processado hoje. Verifique com seu gerente."],
    "EXTRAS (OPTIONAL)": ["pt-BR": "EXTRAS (OPCIONAIS)"],
    "ASSIGN CLEANERS": ["pt-BR": "ATRIBUIR EQUIPE"],
    "Skip for now": ["pt-BR": "Pular por enquanto"],
    "%@ just arrived at %@ for %@.": ["pt-BR": "%@ acabou de chegar em %@ para %@."],
    "%@ completed the %@ at %@. Ready to invoice.": ["pt-BR": "%@ concluiu o %@ em %@. Pronto para faturar."],
    "%@ for %@ is now in progress": ["pt-BR": "%@ para %@ está em andamento"],
    "%@ for %@ was cancelled": ["pt-BR": "%@ para %@ foi cancelado"],
    "%@ for %@ completed by %@": ["pt-BR": "%@ para %@ concluído por %@"],
    "%@ for %@ completed": ["pt-BR": "%@ para %@ concluído"],
    "%@ at %@ — %@. %@": ["pt-BR": "%@ em %@ — %@. %@"],
    "You've collected %@ in total revenue. Keep it up!": ["pt-BR": "Você já arrecadou %@ no total. Continue assim!"],
    "You've collected %@ in total revenue!": ["pt-BR": "Você já arrecadou %@ no total!"],

    // MARK: - Onboarding
    "Welcome to Sweeply": ["pt-BR": "Bem-vindo ao Sweeply"],
    "You're all set. Job reminders will help you stay on schedule.": ["pt-BR": "Está tudo pronto. Os lembretes de serviços vão ajudar você a manter a agenda em dia."],
    "Next": ["pt-BR": "Próximo"],
    "Skip": ["pt-BR": "Pular"],
    "Get Started": ["pt-BR": "Começar"],
    "Let's set up\nyour business": ["pt-BR": "Vamos configurar\nseu negócio"],
    "Your name": ["pt-BR": "Seu nome"],
    "Business name (e.g. Sunrise Cleaning)": ["pt-BR": "Nome do negócio (ex: Limpeza Sunrise)"],
    "Phone (optional)": ["pt-BR": "Telefone (opcional)"],
    "What services\ndo you offer?": ["pt-BR": "Quais serviços\nvocê oferece?"],
    "Prices are fully editable anytime in Settings.": ["pt-BR": "Os preços são editáveis a qualquer momento nas Configurações."],
    "MAIN SERVICES": ["pt-BR": "SERVIÇOS PRINCIPAIS"],
    "ADD-ONS & EXTRAS": ["pt-BR": "ADICIONAIS E EXTRAS"],
    "Scheduling & job tracking": ["pt-BR": "Agendamento e controle de serviços"],
    "Invoicing & payments": ["pt-BR": "Faturamento e pagamentos"],
    "Built for cleaners": ["pt-BR": "Feito para faxineiros"],
    "Open Dashboard": ["pt-BR": "Abrir Painel"],
    "Try Again": ["pt-BR": "Tentar Novamente"],
    "Couldn't save your info — tap to try again.": ["pt-BR": "Não foi possível salvar — toque para tentar novamente."],
    "Stay on top of jobs & invoices": ["pt-BR": "Fique por dentro dos serviços e faturas"],
    "Get reminders before they're due": ["pt-BR": "Receba lembretes antes dos vencimentos"],
    "Welcome to Sweeply,": ["pt-BR": "Bem-vindo ao Sweeply,"],
    "services ready to go": ["pt-BR": "serviços prontos para uso"],
    "service ready to go": ["pt-BR": "serviço pronto para uso"],
    "is all set": ["pt-BR": "está configurado"],
    "Schedule Smarter": ["pt-BR": "Agende com Inteligência"],
    "Get Paid Faster": ["pt-BR": "Receba Mais Rápido"],
    "Scheduling": ["pt-BR": "Agendamento"],
    "Invoicing": ["pt-BR": "Faturamento"],
    "Let's get you set up": ["pt-BR": "Vamos configurar"],
    "Get your workspace ready and start managing jobs with ease.": ["pt-BR": "Prepare seu espaço de trabalho e comece a gerenciar serviços com facilidade."],
    "Build your team": ["pt-BR": "Construa sua equipe"],
    "Invite team members who'll complete jobs with you. You can always add more later.": ["pt-BR": "Convide membros da equipe que completarão serviços com você. Você sempre pode adicionar mais depois."],
    "Invite team members who'll complete jobs with you.": ["pt-BR": "Convide membros da equipe que completarão serviços com você."],
    "Fill in name and email above to add a team member.": ["pt-BR": "Preencha nome e e-mail acima para adicionar um membro da equipe."],
    "SETUP COMPLETE": ["pt-BR": "CONFIGURAÇÃO CONCLUÍDA"],
    "Your business is ready to run.": ["pt-BR": "Seu negócio está pronto para funcionar."],
    "WHAT'S READY": ["pt-BR": "O QUE ESTÁ PRONTO"],
    "Couldn't save — tap to try again.": ["pt-BR": "Não foi possível salvar — toque para tentar novamente."],
    "PENDING INVITES": ["pt-BR": "CONVITES PENDENTES"],

    // MARK: - General Actions
    "Confirm": ["pt-BR": "Confirmar"],
    "Retry": ["pt-BR": "Tentar Novamente"],
    "No results": ["pt-BR": "Sem resultados"],
    "Search": ["pt-BR": "Buscar"],
    "Continue": ["pt-BR": "Continuar"],
    "Create": ["pt-BR": "Criar"],
    "Remove": ["pt-BR": "Remover"],
    "Apply Changes": ["pt-BR": "Aplicar Alterações"],
    "Record": ["pt-BR": "Registrar"],
    "Allow": ["pt-BR": "Permitir"],
    "Today": ["pt-BR": "Hoje"],
    "Tomorrow": ["pt-BR": "Amanhã"],
    "This Week": ["pt-BR": "Esta Semana"],
    "Newest First": ["pt-BR": "Mais Recentes"],
    "Oldest First": ["pt-BR": "Mais Antigos"],
    "Highest Amount": ["pt-BR": "Maior Valor"],
    "Lowest Amount": ["pt-BR": "Menor Valor"],

    // MARK: - Filters
    "Filters": ["pt-BR": "Filtros"],
    "Clear All": ["pt-BR": "Limpar Tudo"],
    "Apply": ["pt-BR": "Aplicar"],
    "Clear": ["pt-BR": "Limpar"],
    "Apply Filters": ["pt-BR": "Aplicar Filtros"],
    "All Statuses": ["pt-BR": "Todos os Status"],

    // MARK: - Auth
    "Sign In": ["pt-BR": "Entrar"],
    "Create Account": ["pt-BR": "Criar Conta"],
    "Forgot password?": ["pt-BR": "Esqueceu a senha?"],
    "Need an account? Create one": ["pt-BR": "Não tem conta? Crie uma"],
    "Already have an account? Sign in": ["pt-BR": "Já tem conta? Entre"],
    "Run your cleaning business.": ["pt-BR": "Gerencie seu negócio de limpeza."],
    "EMAIL": ["pt-BR": "E-MAIL"],
    "PASSWORD": ["pt-BR": "SENHA"],
    "At least 6 characters": ["pt-BR": "Pelo menos 6 caracteres"],
    "Check your email": ["pt-BR": "Verifique seu e-mail"],
    "We sent a reset link to": ["pt-BR": "Enviamos um link de redefinição para"],
    "Check your inbox and follow the instructions.": ["pt-BR": "Verifique sua caixa de entrada e siga as instruções."],
    "Enter your email and we'll send you a reset link.": ["pt-BR": "Digite seu e-mail e enviaremos um link de redefinição."],
    "Send Reset Link": ["pt-BR": "Enviar Link de Redefinição"],
    "Sign Out": ["pt-BR": "Sair"],
    "Signing Out...": ["pt-BR": "Saindo..."],

    // MARK: - Dashboard extended
    "REVENUE THIS WEEK": ["pt-BR": "FATURAMENTO DESTA SEMANA"],
    "No completed jobs yet this week": ["pt-BR": "Nenhum serviço concluído esta semana"],
    "All caught up!": ["pt-BR": "Tudo em dia!"],
    "You're all set": ["pt-BR": "Tudo certo"],
    "Every onboarding step is complete.": ["pt-BR": "Cada etapa está concluída."],
    "Finish every step before you can remove this section.": ["pt-BR": "Conclua cada etapa antes de remover esta seção."],
    "4 of 4 complete": ["pt-BR": "4 de 4 completo"],
    "Performance": ["pt-BR": "Desempenho"],
    "Swipe through your stats": ["pt-BR": "Deslize pelas estatísticas"],
    "Earnings This Week": ["pt-BR": "Ganhos desta Semana"],
    "From completed jobs this week": ["pt-BR": "De serviços concluídos esta semana"],
    "Earnings from completed jobs this month": ["pt-BR": "Ganhos de serviços concluídos este mês"],
    "Completion Rate": ["pt-BR": "Taxa de Conclusão"],
    "Share of your jobs marked complete": ["pt-BR": "Percentual de serviços marcados como concluídos"],
    "On track": ["pt-BR": "No caminho certo"],
    "Keep it up": ["pt-BR": "Continue assim"],
    "No data yet": ["pt-BR": "Sem dados ainda"],
    "Next Job": ["pt-BR": "Próximo Serviço"],
    "Nothing coming up": ["pt-BR": "Nada por vir"],
    "No upcoming jobs scheduled": ["pt-BR": "Nenhum serviço agendado"],
    "When new visits are scheduled, the next one will appear here.": ["pt-BR": "Quando novas visitas forem agendadas, a próxima aparecerá aqui."],
    "Scheduled Revenue": ["pt-BR": "Receita Agendada"],
    "No service mix yet": ["pt-BR": "Sem mix de serviços ainda"],
    "Once jobs are scheduled this month, the service split will show here.": ["pt-BR": "Quando os serviços forem agendados este mês, a divisão de serviços aparecerá aqui."],
    "No client activity yet": ["pt-BR": "Sem atividade de clientes ainda"],
    "Client rankings will update as jobs are completed.": ["pt-BR": "O ranking de clientes será atualizado conforme os serviços forem concluídos."],
"Schedule jobs to see\nservice breakdown": ["pt-BR": "Agende serviços para ver\na divisão de serviços"],
    "Jobs This Month": ["pt-BR": "Serviços Este Mês"],
    "Avg Ticket": ["pt-BR": "Ticket Médio"],

    // MARK: - Schedule extended
    "Day": ["pt-BR": "Dia"],
    "List": ["pt-BR": "Lista"],
    "Month": ["pt-BR": "Mês"],
    "Map": ["pt-BR": "Mapa"],
    "Job Today": ["pt-BR": "Serviço Hoje"],
    "Jobs Today": ["pt-BR": "Serviços Hoje"],
    "Tomorrow: 1 Job": ["pt-BR": "Amanhã: 1 Serviço"],
    "No jobs this day": ["pt-BR": "Nenhum serviço neste dia"],
    "Tap + to schedule a job.": ["pt-BR": "Toque + para agendar um serviço."],
    "Enjoy your day off.": ["pt-BR": "Aproveite seu dia de folga."],
    "No jobs on": ["pt-BR": "Nenhum serviço em"],
    "Tap the date to choose another day.": ["pt-BR": "Toque na data para escolher outro dia."],
    "Nothing scheduled yet.": ["pt-BR": "Nada agendado ainda."],
    "Nothing scheduled.": ["pt-BR": "Nada agendado."],
    "Try clearing the filter.": ["pt-BR": "Tente limpar o filtro."],
    "No matching jobs": ["pt-BR": "Nenhum serviço encontrado"],
    "Try adjusting your filters.": ["pt-BR": "Tente ajustar seus filtros."],
    "INVOICES DUE": ["pt-BR": "FATURAS VENCENDO"],
    "Showing:": ["pt-BR": "Exibindo:"],
    "Jobs for": ["pt-BR": "Serviços de"],
    "job": ["pt-BR": "serviço"],
    "jobs": ["pt-BR": "serviços"],
    "done today": ["pt-BR": "feitos hoje"],
    "next job": ["pt-BR": "próximo serviço"],
    "updated": ["pt-BR": "atualizado"],
    "7-day rev.": ["pt-BR": "receita 7d"],
    "Busy day ahead": ["pt-BR": "Dia cheio"],
    "Starting in 1 Hour": ["pt-BR": "Começando em 1 Hora"],
    "Daily Pay": ["pt-BR": "Pagamento Diário"],
    "Weekly Pay": ["pt-BR": "Pagamento Semanal"],
    "PAYDAY — DAILY PAY": ["pt-BR": "DIA DE PAGAMENTO — DIÁRIO"],
    "PAYDAY — WEEKLY PAY": ["pt-BR": "DIA DE PAGAMENTO — SEMANAL"],
    "JOB STATUS": ["pt-BR": "STATUS DO JOB"],
    "Filter by current job progress": ["pt-BR": "Filtrar por progresso atual do serviço"],
    "SCHEDULE TYPE": ["pt-BR": "TIPO DE AGENDA"],
    "One-time or recurring jobs": ["pt-BR": "Serviços únicos ou recorrentes"],
    "VIEW OPTIONS": ["pt-BR": "OPÇÕES DE EXIBIÇÃO"],
    "Select which tabs appear in the schedule": ["pt-BR": "Selecione quais abas aparecem na agenda"],
    "SHOW CONTENT": ["pt-BR": "EXIBIR CONTEÚDO"],
    "Choose what appears on your schedule": ["pt-BR": "Escolha o que aparece na sua agenda"],
    "Always on": ["pt-BR": "Sempre ativo"],
    "Nothing on": ["pt-BR": "Nada em"],
    "Generate an invoice for": ["pt-BR": "Gerar uma fatura para"],
    "Are you sure you want to delete this job?": ["pt-BR": "Tem certeza que deseja excluir este serviço?"],
    "No photos yet. Tap \"Add Photo\" to attach images.": ["pt-BR": "Nenhuma foto ainda. Toque em \"Adicionar Foto\" para anexar imagens."],
    "Quiet week": ["pt-BR": "Semana tranquila"],

    // MARK: - Clients extended
    "Add Your First Client": ["pt-BR": "Adicione seu Primeiro Cliente"],
    "ARCHIVED": ["pt-BR": "ARQUIVADO"],
    "Archived": ["pt-BR": "Arquivado"],
    "Filter Clients": ["pt-BR": "Filtrar Clientes"],
    "STATUS": ["pt-BR": "STATUS"],
    "Show archived clients": ["pt-BR": "Mostrar clientes arquivados"],
    "SORT BY": ["pt-BR": "ORDENAR POR"],
    "Archive Client": ["pt-BR": "Arquivar Cliente"],
    "Restore Client": ["pt-BR": "Restaurar Cliente"],
    "Delete Client": ["pt-BR": "Excluir Cliente"],
    "This will permanently remove this client. This action cannot be undone.": ["pt-BR": "Isso removerá permanentemente este cliente. Esta ação não pode ser desfeita."],
    "Client deleted": ["pt-BR": "Cliente excluído"],
    "Search conversations": ["pt-BR": "Buscar conversas"],
    "Search clients": ["pt-BR": "Buscar clientes"],
    "Search invoices…": ["pt-BR": "Buscar faturas…"],
    "Start a conversation with": ["pt-BR": "Iniciar uma conversa com"],

    // MARK: - Finances
    "Advanced Finance": ["pt-BR": "Finanças Avançadas"],
    "P&L reports, cash-flow forecasting, and team payroll are available on Pro.": ["pt-BR": "Relatórios P&L, previsão de fluxo de caixa e folha de pagamento estão disponíveis no Pro."],
    "Cash-Flow Forecast": ["pt-BR": "Previsão de Fluxo de Caixa"],
    "Based on scheduled jobs & invoices": ["pt-BR": "Baseado em serviços agendados e faturas"],
    "projected over ": ["pt-BR": "projetado em "],
    " weeks · avg ": ["pt-BR": " semanas · média "],
    "/wk": ["pt-BR": "/semana"],
    "week of ": ["pt-BR": "semana de "],
    "Schedule jobs or send invoices to see your forecast.": ["pt-BR": "Agende serviços ou envie faturas para ver sua previsão."],
    "Upcoming Earnings": ["pt-BR": "Ganhos Futuros"],
    "From completed jobs today": ["pt-BR": "De serviços concluídos hoje"],
    "Total jobs you've completed": ["pt-BR": "Total de serviços que você concluiu"],
    "Great work!": ["pt-BR": "Ótimo trabalho!"],
    "No jobs today": ["pt-BR": "Nenhum serviço hoje"],
    "jobs done this month": ["pt-BR": "serviços feitos este mês"],
    "Potential": ["pt-BR": "Potencial"],
    "No completed jobs yet": ["pt-BR": "Nenhum serviço concluído ainda"],
    "No completed jobs this period": ["pt-BR": "Nenhum serviço concluído neste período"],
    "Payment Amount": ["pt-BR": "Valor do Pagamento"],
    "Profit & Expenses": ["pt-BR": "Lucro e Despesas"],
    "Collected vs outstanding": ["pt-BR": "Recebido vs pendente"],
    "Revenue Overview": ["pt-BR": "Visão de Faturamento"],
    "Team Payroll": ["pt-BR": "Folha de Pagamento"],
    "Setup coverage": ["pt-BR": "Cobertura da configuração"],
    "Configured": ["pt-BR": "Configurado"],
    "Needs setup": ["pt-BR": "Precisa configurar"],
    "Next payday": ["pt-BR": "Próximo pagamento"],
    "Estimated this month": ["pt-BR": "Estimado neste mês"],
    "Tap to set up payroll.": ["pt-BR": "Toque para configurar a folha de pagamento."],
    "Add your crew to start tracking payroll.": ["pt-BR": "Adicione sua equipe para começar a acompanhar a folha de pagamento."],
    "No team members yet": ["pt-BR": "Nenhum membro da equipe ainda"],
    "Rate not set": ["pt-BR": "Taxa não definida"],
    "this period": ["pt-BR": "neste período"],
    "Your Pay Rate": ["pt-BR": "Sua Taxa de Pagamento"],
    "Avg. invoice": ["pt-BR": "Fatura média"],
    "Upcoming jobs value": ["pt-BR": "Valor dos serviços futuros"],
    "No expenses in": ["pt-BR": "Sem despesas em"],

    // MARK: - Job Detail / Cleaner
    "Job Details": ["pt-BR": "Detalhes do Serviço"],
    "Navigate to Job": ["pt-BR": "Navegar até o Serviço"],
    "Check In — I'm Here": ["pt-BR": "Check-in — Cheguei"],
    "Job Check-In": ["pt-BR": "Check-in do Serviço"],
    "ADDRESS": ["pt-BR": "ENDEREÇO"],
    "DURATION": ["pt-BR": "DURAÇÃO"],
    "PAY": ["pt-BR": "PAGAMENTO"],
    "hour": ["pt-BR": "hora"],
    "hours": ["pt-BR": "horas"],
"Job not found": ["pt-BR": "Serviço não encontrado"],
    "Today's Earnings": ["pt-BR": "Ganhos de Hoje"],
    "From": ["pt-BR": "De"],

    // MARK: - Form Fields

    // MARK: - Conversations
    "New Message": ["pt-BR": "Nova Mensagem"],

    // MARK: - Sweeply Pro
    "Sweeply Pro": ["pt-BR": "Sweeply Pro"],
    "Run your cleaning business like a pro.": ["pt-BR": "Gerencie seu negócio de limpeza como um profissional."],
    "Popular": ["pt-BR": "Popular"],
    "PRO": ["pt-BR": "PRO"],
    "MOST POPULAR": ["pt-BR": "MAIS POPULAR"],
    "Get Pro": ["pt-BR": "Adquirir Pro"],
    "STANDARD": ["pt-BR": "PADRÃO"],
    "Get Standard": ["pt-BR": "Adquirir Padrão"],
    "Restore Purchases": ["pt-BR": "Restaurar Compras"],
    "Cancel anytime · Auto-renews · Prices in USD": ["pt-BR": "Cancele a qualquer momento · Renovação automática · Preços em USD"],
    "Upgrade to Pro to unlock this feature.": ["pt-BR": "Atualize para Pro para desbloquear este recurso."],
    "See Plans": ["pt-BR": "Ver Planos"],
    "Upgrade to unlock this feature.": ["pt-BR": "Atualize para desbloquear este recurso."],
    "Manage Subscription": ["pt-BR": "Gerenciar Assinatura"],
    "Unlock Sweeply": ["pt-BR": "Desbloquear Sweeply"],
    "Sweeply is Locked": ["pt-BR": "Sweeply Bloqueado"],
    "Your business data is protected.": ["pt-BR": "Os dados do seu negócio estão protegidos."],

    // MARK: - Widgets
    "NEXT JOB": ["pt-BR": "PRÓXIMO JOB"],
    "TODAY'S SCHEDULE": ["pt-BR": "AGENDA DE HOJE"],
    "All clear today": ["pt-BR": "Livre hoje"],
    "7-day revenue": ["pt-BR": "receita 7 dias"],
    "SWEEPLY": ["pt-BR": "SWEEPLY"],
    "THIS WK": ["pt-BR": "ESTA SEM"],
    "WEEK REVENUE": ["pt-BR": "FATURAMENTO SEMANAL"],
    "7-day earnings": ["pt-BR": "ganhos 7 dias"],
    "TODAY": ["pt-BR": "HOJE"],
    "JOBS TODAY": ["pt-BR": "JOBS HOJE"],
    "TODAY'S VALUE": ["pt-BR": "VALOR DE HOJE"],
    "job today": ["pt-BR": "serviço hoje"],
    "jobs today": ["pt-BR": "serviços hoje"],
    "None completed yet": ["pt-BR": "Nenhum concluído ainda"],

    // MARK: - Schedule
    "Choose Date": ["pt-BR": "Escolher Data"],

    // MARK: - Quick Actions
    "Go Back": ["pt-BR": "Voltar"],
"Job Files": ["pt-BR": "Arquivos do Serviço"],
    "Job Description": ["pt-BR": "Descrição do Serviço"],

    // MARK: - Reports Page (FinancialReportsView)
    "Revenue Progress": ["pt-BR": "Progresso de Faturamento"],
    "Estimated": ["pt-BR": "Estimado"],
    "pending": ["pt-BR": "pendente"],
    "projected over": ["pt-BR": "projetado em"],
    "avg": ["pt-BR": "média"],
    "wk of": ["pt-BR": "sem de"],
    "projected over %d weeks · avg %@/wk": ["pt-BR": "projetado em %d semanas · média %@/sem"],
    "Outstanding invoices": ["pt-BR": "Faturas Pendentes"],
    "Profit & Loss": ["pt-BR": "Lucro e Perda"],
    "Invoices Paid": ["pt-BR": "Faturas Pagas"],
    "Active Clients": ["pt-BR": "Clientes Ativos"],
    "PAYMENT METHODS": ["pt-BR": "METODOS DE PAGAMENTO"],
    "No paid invoices with payment method recorded.": ["pt-BR": "Nenhuma fatura paga com método de pagamento registrado."],
    "View All": ["pt-BR": "Ver Tudo"],
    "Total Projected": ["pt-BR": "Total Projetado"],
    "Select Time Range": ["pt-BR": "Selecionar Período"],
    "Last Month": ["pt-BR": "Último Mês"],
    "Last 3 Months": ["pt-BR": "Últimos 3 Meses"],
    "Last 6 Months": ["pt-BR": "Últimos 6 Meses"],
    "Last 12 Months": ["pt-BR": "Últimos 12 Meses"],
    "Scheduled Jobs": ["pt-BR": "Serviços Agendados"],
    "% vs avg": ["pt-BR": "% vs média"],
    "week forecast": ["pt-BR": "semanas de previsão"],
    "weeks shown": ["pt-BR": "semanas mostradas"],
    "Revenue by Service": ["pt-BR": "Faturamento por Serviço"],
    "All completed jobs": ["pt-BR": "Todos os serviços concluídos"],
    "Complete jobs to see revenue by service.": ["pt-BR": "Complete serviços para ver faturamento por serviço."],
    "EXTRAS & ADD-ONS": ["pt-BR": "EXTRAS E ADICIONAIS"],
    "No custom or add-on services yet": ["pt-BR": "Nenhum serviço adicional ainda"],
    "Payment Methods": ["pt-BR": "Métodos de Pagamento"],
    "TOTAL RECEIVED": ["pt-BR": "TOTAL RECEBIDO"],
    "INVOICES": ["pt-BR": "FATURAS"],
    "No invoices found": ["pt-BR": "Nenhuma fatura encontrada"],
    "Reports": ["pt-BR": "Relatórios"],
    "month": ["pt-BR": "mês"],
    "week": ["pt-BR": "semana"],
    "day": ["pt-BR": "dia"],
    "EXPENSES BY CATEGORY": ["pt-BR": "DESPESAS POR CATEGORIA"],
    "This month": ["pt-BR": "Este mês"],
    "No expenses recorded this month.": ["pt-BR": "Nenhuma despesa registrada neste mês."],
    "REVENUE BY SERVICE": ["pt-BR": "RECEITA POR SERVIÇO"],
    "View": ["pt-BR": "Ver"],
    "JOBS": ["pt-BR": "TRABALHOS"],
    "INVOICE HEALTH": ["pt-BR": "SAÚDE DAS FATURAS"],
    "Collection Rate": ["pt-BR": "Taxa de Cobrança"],
    "INVOICE AGING": ["pt-BR": "ANTIGUIDADE DAS FATURAS"],
    "Avg. time to payment": ["pt-BR": "Tempo médio para pagamento"],
    "Not due yet": ["pt-BR": "Ainda não vencido"],
    "1–7 days overdue": ["pt-BR": "1–7 dias atrasado"],
    "8–30 days": ["pt-BR": "8–30 dias"],
    "30+ days": ["pt-BR": "30+ dias"],
    "Profit": ["pt-BR": "Lucro"],
    "Loss": ["pt-BR": "Prejuízo"],
    "Main Services": ["pt-BR": "Principais Serviços"],
    "SERVICE BREAKDOWN": ["pt-BR": "DETALHAMENTO DE SERVIÇOS"],
    "Revenue %": ["pt-BR": "% Receita"],
    "Cancelled": ["pt-BR": "Cancelado"],
    "Paid": ["pt-BR": "Pago"],
    "Unpaid": ["pt-BR": "Não Pago"],
    "Due": ["pt-BR": "Vencimento"],
    "Amount": ["pt-BR": "Valor"],
    "Client": ["pt-BR": "Cliente"],
    "Date": ["pt-BR": "Data"],
    "Status": ["pt-BR": "Status"],
    "Invoice": ["pt-BR": "Fatura"],
    "Job": ["pt-BR": "Serviço"],
    "No jobs yet": ["pt-BR": "Nenhum serviço ainda"],
    "No clients yet": ["pt-BR": "Nenhum cliente ainda"],
    "Add your first client": ["pt-BR": "Adicione seu primeiro cliente"],
    "Create your first job": ["pt-BR": "Crie seu primeiro serviço"],
    "Total Revenue": ["pt-BR": "Receita Total"],
    "Last Week": ["pt-BR": "Semana Passada"],
    "vs Last Week": ["pt-BR": "vs Semana Passada"],
    "vs Last Month": ["pt-BR": "vs Mês Passado"],
    "To": ["pt-BR": "Até"],
    "Filter": ["pt-BR": "Filtrar"],
    "Loading": ["pt-BR": "Carregando"],
    "Error loading": ["pt-BR": "Erro ao carregar"],
    "Try again": ["pt-BR": "Tentar novamente"],
    "Swipe through your operating metrics": ["pt-BR": "Deslize pelas métricas operacionais"],
    "Invoices sent that haven't been paid yet": ["pt-BR": "Faturas enviadas que ainda não foram pagas"],
    "Clients with visits scheduled this week": ["pt-BR": "Clientes com visitas agendadas esta semana"],
    "Jobs scheduled and completed this week": ["pt-BR": "Serviços agendados e concluídos esta semana"],
    "Average revenue per completed job": ["pt-BR": "Receita média por serviço concluído"],
    "Get started": ["pt-BR": "Começar"],
    "Left": ["pt-BR": "Restantes"],
    "View All Jobs": ["pt-BR": "Ver Todos os Serviços"],
    "View All Schedule": ["pt-BR": "Ver Toda Agenda"],
    "View All Clients": ["pt-BR": "Ver Todos os Clientes"],
    "View All Invoices": ["pt-BR": "Ver Todas as Faturas"],
    "No expenses recorded this period.": ["pt-BR": "Nenhuma despesa registrada neste período."],

    // MARK: - RevenueDetailView
    "Job count": ["pt-BR": "Quantidade de serviços"],
    "Avg per job": ["pt-BR": "Média por serviço"],
    "REVENUE BREAKDOWN": ["pt-BR": "DETALHAMENTO DE RECEITA"],
    "By service type": ["pt-BR": "Por tipo de serviço"],
    "Jobs Completed": ["pt-BR": "Serviços Concluídos"],
    "SERVICE MIX": ["pt-BR": "MIX DE SERVIÇOS"],
    "Jobs by type": ["pt-BR": "Serviços por tipo"],
    "Custom services": ["pt-BR": "Serviços personalizados"],
    "AVG TICKET": ["pt-BR": "TICKET MÉDIO"],
    "Per service type": ["pt-BR": "Por tipo de serviço"],
    "avg %@": ["pt-BR": "média %@"],

    // MARK: - InvoicesDetailListView
    "Paid Invoices": ["pt-BR": "Faturas Pagas"],
    "Overdue Invoices": ["pt-BR": "Faturas Vencidas"],
    "invoice": ["pt-BR": "fatura"],
    "invoices": ["pt-BR": "faturas"],
    "total": ["pt-BR": "total"],
    "No paid invoices": ["pt-BR": "Nenhuma fatura paga"],
    "No outstanding invoices": ["pt-BR": "Nenhuma fatura pendente"],
    "No overdue invoices": ["pt-BR": "Nenhuma fatura vencida"],
    "Due today": ["pt-BR": "Vence hoje"],
    "Due in 1 day": ["pt-BR": "Vence em 1 dia"],
    "Due in %d days": ["pt-BR": "Vence em %d dias"],
    "%d day overdue": ["pt-BR": "%d dia atrasado"],
    "%d days overdue": ["pt-BR": "%d dias atrasados"],
    "Paid %@": ["pt-BR": "Pago em %@"],

    // MARK: - JobsDetailListView
    "Cancelled Jobs": ["pt-BR": "Serviços Cancelados"],
    "job this month": ["pt-BR": "serviço este mês"],
    "jobs this month": ["pt-BR": "serviços este mês"],
    "total value": ["pt-BR": "valor total"],
    "Recurring": ["pt-BR": "Recorrente"],
    "No completed jobs this month": ["pt-BR": "Nenhum serviço concluído este mês"],
    "No upcoming jobs this month": ["pt-BR": "Nenhum serviço próximo este mês"],
    "No cancelled jobs this month": ["pt-BR": "Nenhum serviço cancelado este mês"],

    // MARK: - MemberPaySetupView
    "Pay Setup": ["pt-BR": "Configuração de Pagamento"],
    "Save Setup": ["pt-BR": "Salvar Configuração"],
    "Step %d of %d": ["pt-BR": "Passo %d de %d"],
    "How do you pay %@?": ["pt-BR": "Como você paga %@?"],
    "Choose the pay structure that fits your arrangement.": ["pt-BR": "Escolha a estrutura de pagamento que se adapta ao seu acordo."],
    "Set your rate per service": ["pt-BR": "Defina sua taxa por serviço"],
    "Enter how much you pay for each type of job. Leave blank to skip a service.": ["pt-BR": "Digite quanto você paga por cada tipo de serviço. Deixe em branco para pular."],
    "How much per day?": ["pt-BR": "Quanto por dia?"],
    "How much per week?": ["pt-BR": "Quanto por semana?"],
    "What's the amount for %@?": ["pt-BR": "Qual é o valor para %@?"],
    "This amount is paid for every day they work, regardless of how many jobs.": ["pt-BR": "Este valor é pago por cada dia trabalhado, independente da quantidade de serviços."],
    "This flat amount covers all their work for the week.": ["pt-BR": "Este valor fixo cobre todo o trabalho da semana."],
    "Enter a custom amount you'll pay. You can adjust this at any time.": ["pt-BR": "Digite um valor personalizado. Você pode ajustar a qualquer momento."],
    "Which day do you pay %@?": ["pt-BR": "Qual dia você paga %@?"],
    "They'll receive a notification on this day as a reminder.": ["pt-BR": "Eles receberão uma notificação neste dia como lembrete."],
    "How will you send payment?": ["pt-BR": "Como você enviará o pagamento?"],
    "Choose how you typically pay this team member.": ["pt-BR": "Escolha como você normalmente paga este membro da equipe."],
    "All set! Here's the summary": ["pt-BR": "Tudo pronto! Aqui está o resumo"],
    "Review before saving. You can edit this at any time from the member profile.": ["pt-BR": "Revise antes de salvar. Você pode editar a qualquer momento no perfil do membro."],
    "Pay Type": ["pt-BR": "Tipo de Pagamento"],
    "Rates": ["pt-BR": "Taxas"],
    "Pay Day": ["pt-BR": "Dia de Pagamento"],
    "Via": ["pt-BR": "Via"],
    "None set": ["pt-BR": "Nenhum definido"],
    "service": ["pt-BR": "serviço"],
    "services": ["pt-BR": "serviços"],
    "Sun": ["pt-BR": "Dom"],
    "Mon": ["pt-BR": "Seg"],
    "Tue": ["pt-BR": "Ter"],
    "Wed": ["pt-BR": "Qua"],
    "Thu": ["pt-BR": "Qui"],
    "Fri": ["pt-BR": "Sex"],
    "Sat": ["pt-BR": "Sáb"],
    "Sunday": ["pt-BR": "Domingo"],
    "Monday": ["pt-BR": "Segunda-feira"],
    "Tuesday": ["pt-BR": "Terça-feira"],
    "Wednesday": ["pt-BR": "Quarta-feira"],
    "Thursday": ["pt-BR": "Quinta-feira"],
    "Friday": ["pt-BR": "Sexta-feira"],
    "Saturday": ["pt-BR": "Sábado"],

    // MARK: - SubscriptionPaywallView
    "Monthly": ["pt-BR": "Mensal"],
    "Yearly": ["pt-BR": "Anual"],
    "You're on Sweeply Pro — manage or explore your plan below.": ["pt-BR": "Você está no Sweeply Pro — gerencie ou explore seu plano abaixo."],
    "You're on Standard — upgrade to Pro to unlock everything.": ["pt-BR": "Você está no Padrão — atualize para Pro para desbloquear tudo."],
    "Standard Plan — Active": ["pt-BR": "Plano Padrão — Ativo"],
    "Sweeply Pro — Active": ["pt-BR": "Sweeply Pro — Ativo"],
    "Save 26%": ["pt-BR": "Economize 26%"],
    "/month": ["pt-BR": "/mês"],
    "billed yearly": ["pt-BR": "cobrado anualmente"],
    "Current Plan": ["pt-BR": "Plano Atual"],
    "Manage in App Store": ["pt-BR": "Gerenciar na App Store"],
    "Upgrade to Pro": ["pt-BR": "Atualizar para Pro"],
    "Terms of Service": ["pt-BR": "Termos de Serviço"],
    "Privacy Policy": ["pt-BR": "Política de Privacidade"],
    "Could not load products — check your connection and try again.": ["pt-BR": "Não foi possível carregar os planos — verifique sua conexão e tente novamente."],
    "Purchase failed — please try again.": ["pt-BR": "Compra falhou — tente novamente."],
    "No active subscription found.": ["pt-BR": "Nenhuma assinatura ativa encontrada."],
    "Cancel anytime · Auto-renews · Prices in %@": ["pt-BR": "Cancele a qualquer momento · Renovação automática · Preços em %@"],
    "Pro · Renews %@": ["pt-BR": "Pro · Renova em %@"],
    "%d days left in your free trial": ["pt-BR": "%d dias restantes no período de testes"],
    "Everything in Standard": ["pt-BR": "Tudo do Plano Padrão"],
    "Unlimited cleaners & teams": ["pt-BR": "Limpadores e equipes ilimitados"],
    "Revenue analytics dashboard": ["pt-BR": "Painel de análise de faturamento"],
    "Profit & loss breakdown": ["pt-BR": "Demonstrativo de resultados"],
    "Predictive cash flow": ["pt-BR": "Fluxo de caixa preditivo"],
    "Custom job checklists & notes": ["pt-BR": "Checklists e notas personalizados"],
    "Invoice reminders & tracking": ["pt-BR": "Lembretes e rastreamento de faturas"],
    "Team messaging & job updates": ["pt-BR": "Mensagens da equipe e atualizações de serviços"],
    "Unlimited expense categories": ["pt-BR": "Categorias de despesas ilimitadas"],
    "Unlimited client profiles": ["pt-BR": "Perfis de clientes ilimitados"],
    "Unlimited jobs & invoices": ["pt-BR": "Serviços e faturas ilimitados"],
    "Add up to 3 team members": ["pt-BR": "Adicione até 3 membros da equipe"],
    "Smart calendar & recurring jobs": ["pt-BR": "Calendário inteligente e serviços recorrentes"],
    "Expense categorization": ["pt-BR": "Categorização de despesas"],
    "Home-screen widgets": ["pt-BR": "Widgets na tela inicial"],

    // MARK: - GetStartedView
    "Run your cleaning business with ease. Track jobs, manage clients, and grow your business.": ["pt-BR": "Gerencie seu negócio de limpeza com facilidade. Acompanhe serviços, gerencie clientes e faça seu negócio crescer."],

    // MARK: - CleanerJobDetailView
    "Address": ["pt-BR": "Endereço"],
    "1 hour": ["pt-BR": "1 hora"],
    "%d hours": ["pt-BR": "%d horas"],
    "%.1f hours": ["pt-BR": "%.1f horas"],

    // MARK: - ClientDetailView
    "Call": ["pt-BR": "Ligar"],
    "Navigate": ["pt-BR": "Navegar"],
    "Notes": ["pt-BR": "Notas"],
    "Job History": ["pt-BR": "Histórico de Serviços"],
    "Invoice History": ["pt-BR": "Histórico de Faturas"],
    "No jobs with this client yet": ["pt-BR": "Nenhum serviço com este cliente ainda"],
    "No invoices for this client yet": ["pt-BR": "Nenhuma fatura para este cliente ainda"],
    "upcoming job": ["pt-BR": "próximo serviço"],
    "upcoming jobs": ["pt-BR": "próximos serviços"],
    "Unarchive Client": ["pt-BR": "Restaurar Cliente"],
    "Delete permanently": ["pt-BR": "Excluir permanentemente"],
    "This will permanently remove %@ and all their associated data. This action cannot be undone.": ["pt-BR": "Isso removerá permanentemente %@ e todos os dados associados. Esta ação não pode ser desfeita."],

    // MARK: - CleanerJobsHistoryView
    "Total Earnings": ["pt-BR": "Total de Ganhos"],
    "No jobs found": ["pt-BR": "Nenhum serviço encontrado"],
    "Try changing the filter": ["pt-BR": "Tente mudar o filtro"],

    // MARK: - MarkPaidSheet
    "Payment Method": ["pt-BR": "Método de Pagamento"],
    "Mark as Paid": ["pt-BR": "Marcar como Pago"],
    "Record Payment": ["pt-BR": "Registrar Pagamento"],

    // MARK: - IntroOnboardingView
    "Your Cleaning Business.\nIn Control.": ["pt-BR": "Seu Negócio de Limpeza.\nSob Controle."],
    "Jobs, clients, and payments - organized in one place.": ["pt-BR": "Serviços, clientes e pagamentos — organizados em um só lugar."],
    "Create jobs, assign cleaners, and track status in real time.": ["pt-BR": "Crie serviços, atribua limpadores e acompanhe o status em tempo real."],
    "Send invoices and track paid, unpaid, and overdue balances.": ["pt-BR": "Envie faturas e acompanhe saldos pagos, pendentes e vencidos."],

    // MARK: - ProductTutorialView
    "SCHEDULING": ["pt-BR": "AGENDAMENTO"],
    "INVOICING": ["pt-BR": "FATURAMENTO"],
    "YOU'RE READY": ["pt-BR": "VOCÊ ESTÁ PRONTO"],
    "Book a job in\n20 seconds.": ["pt-BR": "Agende um serviço em\n20 segundos."],
    "Send invoices.\nGet paid.": ["pt-BR": "Envie faturas.\nReceba."],
    "Let's go.": ["pt-BR": "Vamos lá."],
    "Run jobs. Get paid. Grow.": ["pt-BR": "Gerencie serviços. Receba. Cresça."],

    // MARK: - OnboardingView (late additions)
    "Previous": ["pt-BR": "Anterior"],
    "Tell us about\nyour business": ["pt-BR": "Fale sobre\nseu negócio"],
    "Stay in the loop": ["pt-BR": "Fique por dentro"],
    "Get notified about upcoming jobs, payments, and team updates.": ["pt-BR": "Receba notificações sobre serviços, pagamentos e atualizações da equipe."],
    "Enable Notifications": ["pt-BR": "Ativar Notificações"],
    "Maybe later": ["pt-BR": "Talvez depois"],
    "30 days free,\nthen choose your plan.": ["pt-BR": "30 dias grátis,\ndepois escolha seu plano."],
    "No payment needed until your trial ends.": ["pt-BR": "Nenhum pagamento necessário até o fim do período de testes."],
    "I'll decide later": ["pt-BR": "Decidirei depois"],
    "Your free trial starts today": ["pt-BR": "Seu período de testes começa hoje"],
    "Start Free Trial": ["pt-BR": "Iniciar Período de Testes"],
    "Quickly find nearby jobs and get directions to your clients.": ["pt-BR": "Encontre serviços próximos e obtenha direções para seus clientes."],
    "Enable your location": ["pt-BR": "Ative sua localização"],
    "Enable Location": ["pt-BR": "Ativar Localização"],
    "%@, your business is ready.": ["pt-BR": "%@, seu negócio está pronto."],
    "Start booking jobs, sending invoices, and getting paid.": ["pt-BR": "Comece a agendar serviços, enviar faturas e receber pagamentos."],

    // MARK: - BusinessView / TeamView
    "Join": ["pt-BR": "Participar"],
    "TEAMS": ["pt-BR": "EQUIPES"],
    "You're on Pro": ["pt-BR": "Você está no Pro"],
    "Add unlimited team members to your business.": ["pt-BR": "Adicione membros ilimitados ao seu negócio."],
    "Invited you as %@": ["pt-BR": "Convidou você como %@"],
    "Member since %@": ["pt-BR": "Membro desde %@"],
    "Jobs will appear here once %@ is assigned work": ["pt-BR": "Os serviços aparecerão aqui quando %@ receber trabalhos"],

    // MARK: - InvoiceDetailView / NewInvoiceView / JobDetailView
    "SERVICES": ["pt-BR": "SERVIÇOS"],
    "TOTAL": ["pt-BR": "TOTAL"],
    "EXTRAS": ["pt-BR": "EXTRAS"],
    "PHOTOS": ["pt-BR": "FOTOS"],
    "This will permanently delete %@. This can't be undone.": ["pt-BR": "Isso excluirá permanentemente %@. Esta ação não pode ser desfeita."],

    // MARK: - NewJobView
    "You can still schedule this job.": ["pt-BR": "Você ainda pode agendar este serviço."],
    "days": ["pt-BR": "dias"],

    // MARK: - ExpensesView
    "Track supplies, fuel, equipment,\nand every business cost here.": ["pt-BR": "Registre suprimentos, combustível, equipamentos\ne todos os custos do negócio aqui."],

    // MARK: - CleanerSettingsView / AuthView
    "Something went wrong — try again.": ["pt-BR": "Algo deu errado — tente novamente."],
    "or": ["pt-BR": "ou"],
    "at": ["pt-BR": "às"],

    // MARK: - DashboardView / CleanerFinanceView / FinancesView
    "Revenue this week": ["pt-BR": "Faturamento desta semana"],

    // MARK: - Button labels (late additions)
    "Clear Search": ["pt-BR": "Limpar Busca"],
    "Add Extra": ["pt-BR": "Adicionar Extra"],
    "Add Service": ["pt-BR": "Adicionar Serviço"],
    "Start Job": ["pt-BR": "Iniciar Serviço"],
    "Cancel Job": ["pt-BR": "Cancelar Serviço"],
    "Payments": ["pt-BR": "Pagamentos"],
    "Mark as %@": ["pt-BR": "Marcar como %@"],

    // MARK: - Localization Audit Fixes
    "English": ["pt-BR": "Inglês"],
    "Português (Brasil)": ["pt-BR": "Português (Brasil)"],
    "Your business, right where you left it.": ["pt-BR": "Seu negócio, exatamente de onde você parou."],
    "your@email.com": ["pt-BR": "seu@email.com"],
    "Enter your\npassword": ["pt-BR": "Digite sua\nsenha"],
    "Signing in…": ["pt-BR": "Entrando…"],
    "Pay %@": ["pt-BR": "Pagar %@"],
    "Schedule jobs to see\nclient mix": ["pt-BR": "Agende serviços para ver\na mistura de clientes"],
    "Hidden — tap to show": ["pt-BR": "Oculto — toque para mostrar"],
    "Overdue 1 day": ["pt-BR": "Vencido há 1 dia"],
    "Overdue %d days": ["pt-BR": "Vencido há %d dias"],
    "Add Expense": ["pt-BR": "Adicionar Despesa"],
    "Cash flow": ["pt-BR": "Fluxo de caixa"],
    "Payment due": ["pt-BR": "Pagamento devido"],
    "Sort": ["pt-BR": "Ordenar"],
    "No invoices yet": ["pt-BR": "Nenhuma fatura ainda"],
    "No %d invoices": ["pt-BR": "Nenhuma %d fatura"],
    "This Year": ["pt-BR": "Este ano"],
    "Scheduled jobs & invoices": ["pt-BR": "Serviços e faturas agendados"],
    "Catalog services": ["pt-BR": "Serviços do catálogo"],
    "Add-Ons": ["pt-BR": "Add-ons"],
    "Avg Price": ["pt-BR": "Preço médio"],
    "No services yet": ["pt-BR": "Nenhum serviço ainda"],
    "No extras yet": ["pt-BR": "Nenhum extra ainda"],
    "Primary services offered": ["pt-BR": "Serviços principais oferecidos"],
    "Add-ons charged on top of the main service": ["pt-BR": "Add-ons cobrados além do serviço principal"],
    "Add another service": ["pt-BR": "Adicionar outro serviço"],
    "Add extra service": ["pt-BR": "Adicionar serviço extra"],
    "Add add-ons or custom services to your catalog.": ["pt-BR": "Adicione add-ons ou serviços personalizados ao seu catálogo."],
    "Add services to your catalog to see revenue by service.": ["pt-BR": "Adicione serviços ao seu catálogo para ver o faturamento por serviço."],
    "Service Catalog": ["pt-BR": "Catálogo de Serviços"],
    "Invite": ["pt-BR": "Convidar"],
    "Invite Cleaner": ["pt-BR": "Convidar Limpador"],
    "My Team": ["pt-BR": "Minha Equipe"],
    "No cleaners yet": ["pt-BR": "Nenhum limpador ainda"],
    "Tap Invite to add your first cleaner": ["pt-BR": "Toque em Convidar para adicionar seu primeiro limpador"],
    "Team": ["pt-BR": "Equipe"],
    "Team Member": ["pt-BR": "Membro da Equipe"],
    "Everything is ready": ["pt-BR": "Tudo está pronto"],
    "Clients and team tools are ready": ["pt-BR": "Clientes e ferramentas da equipe estão prontos"],
    "Invoices and payments are ready": ["pt-BR": "Faturas e pagamentos estão prontos"],
    "Reports and finances are unlocked": ["pt-BR": "Relatórios e finanças estão liberados"],
    "Team tools are unlocked": ["pt-BR": "As ferramentas da equipe estão liberadas"],
    "ACCOUNT": ["pt-BR": "CONTA"],
    "AMOUNT": ["pt-BR": "VALOR"],
    "Account owner": ["pt-BR": "Dono da conta"],
    "Add & Share Invite": ["pt-BR": "Adicionar e Compartilhar Convite"],
    "Add Extras": ["pt-BR": "Adicionar Extras"],
    "Add First Extra": ["pt-BR": "Adicionar Primeiro Extra"],
    "Add First Service": ["pt-BR": "Adicionar Primeiro Serviço"],
    "Add Photo": ["pt-BR": "Adicionar Foto"],
    "Add-on charged on top of the main service": ["pt-BR": "Add-on cobrado além do serviço principal"],
    "All features are included": ["pt-BR": "Todos os recursos estão incluídos"],
    "Already Paid": ["pt-BR": "Já pago"],
    "Assign Cleaner": ["pt-BR": "Atribuir Limpador"],
    "Assigned To": ["pt-BR": "Atribuído a"],
    "BILLED TO": ["pt-BR": "COBRAR PARA"],
    "BUSINESS ADDRESS": ["pt-BR": "ENDEREÇO DO NEGÓCIO"],
    "Biweekly": ["pt-BR": "Quinzenal"],
    "Business Snapshot": ["pt-BR": "Resumo do negócio"],
    "By Category": ["pt-BR": "Por categoria"],
    "CLIENT PROFILE": ["pt-BR": "PERFIL DO CLIENTE"],
    "CONTACT INFO": ["pt-BR": "INFORMAÇÕES DE CONTATO"],
    "Category": ["pt-BR": "Categoria"],
    "Choose from your catalog to build the invoice": ["pt-BR": "Escolha do seu catálogo para montar a fatura"],
    "Cleaner": ["pt-BR": "Limpador"],
    "Client *": ["pt-BR": "Cliente *"],
    "Client not found": ["pt-BR": "Cliente não encontrado"],
    "Complete Job": ["pt-BR": "Concluir Serviço"],
    "Create Invoice": ["pt-BR": "Criar Fatura"],
    "Custom": ["pt-BR": "Personalizado"],
    "Custom Line Item": ["pt-BR": "Item Personalizado"],
    "Customize": ["pt-BR": "Personalizar"],
    "DOCUMENT DETAILS": ["pt-BR": "DETALHES DO DOCUMENTO"],
    "Date *": ["pt-BR": "Data *"],
    "Day Total": ["pt-BR": "Total do Dia"],
    "Day's Expenses": ["pt-BR": "Despesas do Dia"],
    "Delete Invoice": ["pt-BR": "Excluir Fatura"],
    "Description": ["pt-BR": "Descrição"],
    "Directions": ["pt-BR": "Direções"],
    "Due Date": ["pt-BR": "Data de Vencimento"],
    "Duration (hrs)": ["pt-BR": "Duração (hrs)"],
    "EARNINGS THIS WEEK": ["pt-BR": "GANHOS ESTA SEMANA"],
    "Edit Client": ["pt-BR": "Editar Cliente"],
    "Edit Dashboard": ["pt-BR": "Editar Painel"],
    "Edit Invoice": ["pt-BR": "Editar Fatura"],
    "Enable Face ID": ["pt-BR": "Ativar Face ID"],
    "Enter a price greater than $0": ["pt-BR": "Digite um preço maior que $0"],
    "Every": ["pt-BR": "A cada"],
    "Extra Cost": ["pt-BR": "Custo Extra"],
    "Filter data": ["pt-BR": "Filtrar dados"],
    "Invoice Details": ["pt-BR": "Detalhes da Fatura"],
    "Invoice Health": ["pt-BR": "Saúde das Faturas"],
    "Invoice No.": ["pt-BR": "Fatura Nº"],
    "Invoice Preview": ["pt-BR": "Prévia da Fatura"],
    "Invoice not found": ["pt-BR": "Fatura não encontrada"],
    "JOB DEFAULTS": ["pt-BR": "PADRÕES DE JOB"],
    "JOB DETAILS": ["pt-BR": "DETALHES DO JOB"],
    "JOB EXTRAS": ["pt-BR": "EXTRAS DO JOB"],
    "JOB HISTORY": ["pt-BR": "HISTÓRICO DE JOBS"],
    "Job date must be in the future": ["pt-BR": "A data do serviço deve estar no futuro"],
    "Jobs scheduled this week": ["pt-BR": "Serviços agendados esta semana"],
    "Log out of Sweeply?": ["pt-BR": "Sair do Sweeply?"],
    "NOTES (OPTIONAL)": ["pt-BR": "NOTAS (OPCIONAL)"],
    "New Expense": ["pt-BR": "Nova Despesa"],
    "New Invoice": ["pt-BR": "Nova Fatura"],
    "New Job": ["pt-BR": "Novo Serviço"],
    "Next occurrences": ["pt-BR": "Próximas ocorrências"],
    "No active clients. Add a client first.": ["pt-BR": "Nenhum cliente ativo. Adicione um cliente primeiro."],
    "No jobs assigned yet": ["pt-BR": "Nenhum serviço atribuído ainda"],
    "No jobs match your search": ["pt-BR": "Nenhum serviço corresponde à sua busca"],
    "No payments received yet": ["pt-BR": "Nenhum pagamento recebido ainda"],
    "No payments recorded yet": ["pt-BR": "Nenhum pagamento registrado ainda"],
    "None": ["pt-BR": "Nenhum"],
    "Not Now": ["pt-BR": "Agora não"],
    "Notes (optional)": ["pt-BR": "Notas (opcional)"],
    "OPERATIONAL NOTES": ["pt-BR": "NOTAS OPERACIONAIS"],
    "One-time": ["pt-BR": "Uma vez"],
    "PAY SETUP": ["pt-BR": "CONFIGURAÇÃO DE PAGAMENTO"],
    "PAY VIA": ["pt-BR": "PAGAR VIA"],
    "PAYMENT HISTORY": ["pt-BR": "HISTÓRICO DE PAGAMENTOS"],
    "PROPERTY INSTRUCTIONS": ["pt-BR": "INSTRUÇÕES DO IMÓVEL"],
    "Partial": ["pt-BR": "Parcial"],
    "Pay due": ["pt-BR": "Pagamento devido"],
    "Payments you've recorded": ["pt-BR": "Pagamentos que você registrou"],
    "Pending": ["pt-BR": "Pendente"],
    "Per Day": ["pt-BR": "Por Dia"],
    "Per Job": ["pt-BR": "Por Serviço"],
    "Per Week": ["pt-BR": "Por Semana"],
    "Performance Overview": ["pt-BR": "Visão de desempenho"],
    "Please select a client": ["pt-BR": "Selecione um cliente"],
    "Preferred Service": ["pt-BR": "Serviço Preferido"],
    "Price": ["pt-BR": "Preço"],
    "Price ($)": ["pt-BR": "Preço ($)"],
    "Quantity": ["pt-BR": "Quantidade"],
    "Re-open Job": ["pt-BR": "Reabrir Serviço"],
    "Recent Jobs": ["pt-BR": "Serviços Recentes"],
    "Remove from Team": ["pt-BR": "Remover da Equipe"],
    "Resend email": ["pt-BR": "Reenviar e-mail"],
    "SERVICE ADDRESS": ["pt-BR": "ENDEREÇO DO SERVIÇO"],
    "SERVICE CATALOG": ["pt-BR": "CATÁLOGO DE SERVIÇOS"],
    "Save Changes": ["pt-BR": "Salvar Alterações"],
    "Save Contact Info": ["pt-BR": "Salvar Informações de Contato"],
    "Save Expense": ["pt-BR": "Salvar Despesa"],
    "Schedule a Job": ["pt-BR": "Agendar um Serviço"],
    "Scheduling is ready": ["pt-BR": "O agendamento está pronto"],
    "Select Service...": ["pt-BR": "Selecionar Serviço..."],
    "Select State": ["pt-BR": "Selecionar Estado"],
    "Select a service or extra": ["pt-BR": "Selecione um serviço ou extra"],
    "Send": ["pt-BR": "Enviar"],
    "Service Distribution": ["pt-BR": "Distribuição de Serviços"],
    "Service Name": ["pt-BR": "Nome do Serviço"],
    "Service Type *": ["pt-BR": "Tipo de Serviço *"],
    "Set Up": ["pt-BR": "Configurar"],
    "Set end date": ["pt-BR": "Definir data final"],
    "Share": ["pt-BR": "Compartilhar"],
    "Sign in without a password": ["pt-BR": "Entrar sem senha"],
    "Sign out": ["pt-BR": "Sair"],
    "Sign out of Sweeply?": ["pt-BR": "Sair do Sweeply?"],
    "Skip to dashboard": ["pt-BR": "Pular para o painel"],
    "Subtotal": ["pt-BR": "Subtotal"],
    "Sweeply no longer uses paywalls or subscription purchases in this build.": ["pt-BR": "O Sweeply não usa mais paywalls nem compras de assinatura nesta versão."],
    "Switch": ["pt-BR": "Mudar"],
    "TEAM INVITES": ["pt-BR": "CONVITES DA EQUIPE"],
    "THIS MONTH": ["pt-BR": "ESTE MÊS"],
    "Tap Record to log a payment": ["pt-BR": "Toque em Registrar para lançar um pagamento"],
    "Tap Record to log a payment to %@": ["pt-BR": "Toque em Registrar para lançar um pagamento para %@"],
    "Tap the link to verify your account and sign in.": ["pt-BR": "Toque no link para verificar sua conta e entrar."],
    "Text": ["pt-BR": "Texto"],
    "There’s no subscription setup here anymore. Finish onboarding and start using every part of Sweeply.": ["pt-BR": "Não há mais configuração de assinatura aqui. Conclua o onboarding e comece a usar todas as partes do Sweeply."],
    "This will remove them from your roster. You can invite them again anytime.": ["pt-BR": "Isso os removerá da sua equipe. Você poderá convidá-los novamente a qualquer momento."],
    "Time *": ["pt-BR": "Hora *"],
    "Top Clients": ["pt-BR": "Principais Clientes"],
    "Total Spent": ["pt-BR": "Total Gasto"],
    "Transactions": ["pt-BR": "Transações"],
    "Unassigned": ["pt-BR": "Não atribuído"],
    "Unit Price ($)": ["pt-BR": "Preço Unitário ($)"],
    "View All %d Expenses": ["pt-BR": "Ver Todas as %d Despesas"],
    "View All %d Invoices": ["pt-BR": "Ver Todas as %d Faturas"],
    "View All %d Jobs": ["pt-BR": "Ver Todos os %d Serviços"],
    "View All %d Payments": ["pt-BR": "Ver Todos os %d Pagamentos"],
    "View Profile": ["pt-BR": "Ver Perfil"],
    "We sent a confirmation link to:": ["pt-BR": "Enviamos um link de confirmação para:"],
    "Weekly": ["pt-BR": "Semanal"],
    "Work this cleaner has done": ["pt-BR": "Trabalho que este limpador fez"],
    "You can invite them again anytime.": ["pt-BR": "Você pode convidá-los novamente a qualquer momento."],
    "You have %d jobs": ["pt-BR": "Você tem %d serviços"],
    "You're all clear today": ["pt-BR": "Você está livre hoje"],
    "job all time": ["pt-BR": "serviço de todo o período"],
    "job in last 6 months": ["pt-BR": "serviço nos últimos 6 meses"],
    "job this week": ["pt-BR": "serviço esta semana"],
    "jobs all time": ["pt-BR": "serviços de todo o período"],
    "jobs in last 6 months": ["pt-BR": "serviços nos últimos 6 meses"],
    "jobs this week": ["pt-BR": "serviços esta semana"],
    "Add small add-ons like laundry, dishes, or window cleaning — these appear as extras when booking a job.": ["pt-BR": "Adicione pequenos extras como lavanderia, louça ou limpeza de janelas — eles aparecem como extras ao agendar um serviço."],
    "Delete Client?": ["pt-BR": "Excluir Cliente?"],
    "English · Português (Brasil)": ["pt-BR": "English · Português (Brasil)"],
    "Forgot Password?": ["pt-BR": "Esqueceu a Senha?"],
    "Import from Contacts": ["pt-BR": "Importar dos Contatos"],
    "Invite as many team members as your business needs.": ["pt-BR": "Convide quantos membros da equipe o seu negócio precisar."],
    "No %@ jobs": ["pt-BR": "Nenhum serviço %@"],
    "No %@ jobs in the last 6 months": ["pt-BR": "Nenhum serviço %@ nos últimos 6 meses"],
    "No %@ jobs this month": ["pt-BR": "Nenhum serviço %@ este mês"],
    "No %@ jobs this week": ["pt-BR": "Nenhum serviço %@ esta semana"],
    "Record %@": ["pt-BR": "Registrar %@"],
    "Sample Card Content": ["pt-BR": "Conteúdo de Exemplo do Card"],
    "To %@": ["pt-BR": "Para %@"],
    "Total:": ["pt-BR": "Total:"],
    "on": ["pt-BR": "em"],
    "%@ collected": ["pt-BR": "%@ recebido"],
    "%@ estimated": ["pt-BR": "%@ estimado"],
    "%d of 4 complete": ["pt-BR": "%d de 4 concluídos"],
    "Collapse get started": ["pt-BR": "Recolher introdução"],
    "Expand get started": ["pt-BR": "Expandir introdução"],
    "Hide get started": ["pt-BR": "Ocultar introdução"],
    "From %@": ["pt-BR": "De %@"],
    "Jobs for %@": ["pt-BR": "Serviços para %@"],
    "Great work — you've wrapped up everything on your schedule.": ["pt-BR": "Ótimo trabalho — você concluiu tudo na sua agenda."],
    "Every job on this day was completed.": ["pt-BR": "Todos os serviços deste dia foram concluídos."],
    "%d job completed": ["pt-BR": "%d serviço concluído"],
    "%d jobs completed": ["pt-BR": "%d serviços concluídos"],
    "Link expires in %@": ["pt-BR": "O link expira em %@"],
    "Waiting for verification%@": ["pt-BR": "Aguardando verificação%@"],
    "We sent a reset link to %@. Check your inbox and follow the instructions.": ["pt-BR": "Enviamos um link de redefinição para %@. Verifique sua caixa de entrada e siga as instruções."],
    "%d expense in %@": ["pt-BR": "%d despesa em %@"],
    "%d expenses in %@": ["pt-BR": "%d despesas em %@"],
    "No expenses in %@": ["pt-BR": "Nenhuma despesa em %@"],
    "%d visit this month": ["pt-BR": "%d visita este mês"],
    "%d visits this month": ["pt-BR": "%d visitas este mês"],
    "+ %d more": ["pt-BR": "+ %d mais"],
    "%d shown": ["pt-BR": "%d exibidos"],
    "%d member": ["pt-BR": "%d membro"],
    "%d members": ["pt-BR": "%d membros"],
    "%d jobs done": ["pt-BR": "%d serviços concluídos"],
    "Based on all %d completed jobs": ["pt-BR": "Com base em todos os %d serviços concluídos"],
    "Outstanding Balance": ["pt-BR": "Saldo pendente"],
    "All on track": ["pt-BR": "Tudo em dia"],
    "%d overdue": ["pt-BR": "%d atrasadas"],
    "%d open invoice": ["pt-BR": "%d fatura em aberto"],
    "%d open invoices": ["pt-BR": "%d faturas em aberto"],
    "Active week": ["pt-BR": "Semana ativa"],
    "%d total client on your roster": ["pt-BR": "%d cliente total na sua carteira"],
    "%d total clients on your roster": ["pt-BR": "%d clientes totais na sua carteira"],
    "%d completed": ["pt-BR": "%d concluídos"],
    "%d job done this month": ["pt-BR": "%d serviço concluído este mês"],
    "%d jobs done this month": ["pt-BR": "%d serviços concluídos este mês"],
    "All time completed jobs": ["pt-BR": "Serviços concluídos no total"],
    "%d job in next 7 days": ["pt-BR": "%d serviço nos próximos 7 dias"],
    "%d jobs in next 7 days": ["pt-BR": "%d serviços nos próximos 7 dias"],
    "No %@ invoices": ["pt-BR": "Nenhuma fatura %@"],
    "Your first invoice will appear here once created.": ["pt-BR": "Sua primeira fatura aparecerá aqui quando for criada."],
    "Try a different filter to see more invoices.": ["pt-BR": "Tente um filtro diferente para ver mais faturas."],
    "Due %@": ["pt-BR": "Vence %@"],
    "%d invoice": ["pt-BR": "%d fatura"],
    "%d invoices": ["pt-BR": "%d faturas"],
    "%d%% vs avg": ["pt-BR": "%d%% vs média"],
    "(%@/wk)": ["pt-BR": "(%@/sem)"],
    "%d week forecast": ["pt-BR": "Previsão de %d semana"],
    "%d weeks shown": ["pt-BR": "%d semanas exibidas"],
    "%d service": ["pt-BR": "%d serviço"],
    "%d services": ["pt-BR": "%d serviços"],
    "%d item": ["pt-BR": "%d item"],
    "%d items": ["pt-BR": "%d itens"],
    "%d service configured": ["pt-BR": "%d serviço configurado"],
    "%d services configured": ["pt-BR": "%d serviços configurados"],
    "%d extra configured": ["pt-BR": "%d extra configurado"],
    "%d extras configured": ["pt-BR": "%d extras configurados"],
    "Completed jobs": ["pt-BR": "Serviços concluídos"],
    "Upcoming value": ["pt-BR": "Valor futuro"],
    "All-time paid": ["pt-BR": "Pago no total"],
    "%d still in flight": ["pt-BR": "%d ainda em andamento"],
    "Based on completed visits this month": ["pt-BR": "Com base nas visitas concluídas este mês"],
    "Open invoices waiting to be collected": ["pt-BR": "Faturas em aberto aguardando recebimento"],
    "%d%% of this month's bookings": ["pt-BR": "%d%% dos agendamentos deste mês"],
    "Schedule your first job": ["pt-BR": "Agende seu primeiro serviço"],
    "Create your first invoice": ["pt-BR": "Crie sua primeira fatura"],
    "Set up business profile": ["pt-BR": "Configure o perfil do negócio"],
    "Issued": ["pt-BR": "Emitida"],
    "%d total clients": ["pt-BR": "%d clientes no total"],
    "%d active clients": ["pt-BR": "%d clientes ativos"],
    "Phone number must be at least 10 digits": ["pt-BR": "O número de telefone deve ter pelo menos 10 dígitos"],
    "Gate code #1234...": ["pt-BR": "Código do portão #1234..."],
    "Team Update": ["pt-BR": "Atualização da equipe"],
    "Invoice sync issue": ["pt-BR": "Problema de sincronização de faturas"],
    "Full name": ["pt-BR": "Nome completo"],
    "email@example.com": ["pt-BR": "email@exemplo.com"],
    "Not set": ["pt-BR": "Não definido"],
    "%d total": ["pt-BR": "%d total"],
    "Resend Invite": ["pt-BR": "Reenviar convite"],
    "Mark as Active": ["pt-BR": "Marcar como ativo"],
    "Mark as Inactive": ["pt-BR": "Marcar como inativo"],
    "Select client": ["pt-BR": "Selecionar cliente"],
    "Time overlap with %@'s job (%@ – %@)": ["pt-BR": "Conflito de horário com o serviço de %@ (%@ – %@)"],
    "CLIENT": ["pt-BR": "CLIENTE"],
    "Bill to": ["pt-BR": "Cobrar de"],
    "INVOICE DETAILS": ["pt-BR": "DETALHES DA FATURA"],
    "PAYMENT": ["pt-BR": "PAGAMENTO"],
    "e.g. April monthly clean + oven detail": ["pt-BR": "ex.: limpeza mensal de abril + limpeza do forno"],
    "Unknown Client": ["pt-BR": "Cliente desconhecido"],
    "Failed to create invoice.": ["pt-BR": "Não foi possível criar a fatura."],
    "Service description": ["pt-BR": "Descrição do serviço"],
    "e.g. Extra hours, Supplies, etc.": ["pt-BR": "ex.: horas extras, materiais, etc."],
    "No phone listed": ["pt-BR": "Sem telefone cadastrado"],
    "Entry": ["pt-BR": "Entrada"],
    "Internal Notes": ["pt-BR": "Notas internas"],
    "Location": ["pt-BR": "Local"],
    "No address provided": ["pt-BR": "Nenhum endereço informado"],
    "%@ at %@ — %@": ["pt-BR": "%@ em %@ — %@"],
    "New Job Assigned": ["pt-BR": "Novo serviço atribuído"],
    "Unread (%d)": ["pt-BR": "Não lidas (%d)"],
    "WEEKLY PAYDAY": ["pt-BR": "PAGAMENTO SEMANAL"],
    "Delete Job?": ["pt-BR": "Excluir serviço?"],
    "Create Invoice?": ["pt-BR": "Criar fatura?"],
    "You're all set — job reminders and schedule updates will appear here.": ["pt-BR": "Tudo pronto — lembretes de serviços e atualizações da agenda aparecerão aqui."],
    "Failed to synchronize notifications.": ["pt-BR": "Não foi possível sincronizar as notificações."],
    "Invoice Paid": ["pt-BR": "Fatura paga"],
    "Invoice Overdue": ["pt-BR": "Fatura atrasada"],
    "Invoice due in 3 days": ["pt-BR": "Fatura vence em 3 dias"],
    "Invoice due today": ["pt-BR": "Fatura vence hoje"],
    "Invoice Due Today": ["pt-BR": "Fatura Vence Hoje"],
    "2 Invoices Due Today": ["pt-BR": "2 Faturas Vencem Hoje"],
    "%d Invoices Due Today": ["pt-BR": "%d Faturas Vencem Hoje"],
    "Invoice seriously overdue": ["pt-BR": "Fatura gravemente atrasada"],
    "Invoice Reminder": ["pt-BR": "Lembrete de fatura"],
    "%@ for %@ — due today": ["pt-BR": "%@ para %@ — vence hoje"],
    "%@ for %@ and %@ for %@ — due today": ["pt-BR": "%@ para %@ e %@ para %@ — vencem hoje"],
    "%d invoices due today — starting with %@": ["pt-BR": "%d faturas vencem hoje — começando com %@"],
    "Remind in 3 days": ["pt-BR": "Lembrar em 3 dias"],
    "%@ for %@ — marked complete": ["pt-BR": "%@ para %@ — marcado como concluído"],
    "%@ for %@ — %@ received": ["pt-BR": "%@ para %@ — %@ recebido"],
    "%@ for %@ — %@ overdue": ["pt-BR": "%@ para %@ — %@ atrasado"],
    "Sweeply Notifications": ["pt-BR": "Notificações Sweeply"],
    "Everything is working — you'll get reminders for jobs and invoices here.": ["pt-BR": "Está tudo funcionando — você receberá lembretes de serviços e faturas aqui."],
    "%@ for %@ at %@": ["pt-BR": "%@ para %@ às %@"],
    "%@ for %@ starts at %@": ["pt-BR": "%@ para %@ começa às %@"],
    "Quiet Week Ahead": ["pt-BR": "Semana calma pela frente"],
    "No jobs scheduled this week. Great time to reach out to clients!": ["pt-BR": "Nenhum serviço agendado esta semana. Ótimo momento para entrar em contato com clientes!"],
    "2 Jobs Today": ["pt-BR": "2 serviços hoje"],
    "%d Jobs Today": ["pt-BR": "%d serviços hoje"],
    "%@ at %@, then %@ at %@": ["pt-BR": "%@ às %@, depois %@ às %@"],
    "Starting at %@ with %@ — tap to see your full schedule": ["pt-BR": "Começando às %@ com %@ — toque para ver sua agenda completa"],
    "Tomorrow: 2 Jobs": ["pt-BR": "Amanhã: 2 serviços"],
    "Tomorrow: %d Jobs": ["pt-BR": "Amanhã: %d serviços"],
    "%@ at %@ and %@ at %@": ["pt-BR": "%@ às %@ e %@ às %@"],
    "%@–%@ — starting with %@": ["pt-BR": "%@–%@ — começando com %@"],
    "Weekly Earnings Summary": ["pt-BR": "Resumo semanal de ganhos"],
    "You earned %@ last week. Open Finance for your full breakdown.": ["pt-BR": "Você ganhou %@ na semana passada. Abra Finanças para ver o detalhamento completo."],
    "No earnings recorded last week. Open Finance to review your invoices.": ["pt-BR": "Nenhum ganho registrado na semana passada. Abra Finanças para revisar suas faturas."],
    "Time to Pay %@": ["pt-BR": "Hora de pagar %@"],
    "%@ is owed %@ today. Open Sweeply to record the payment.": ["pt-BR": "%@ deve receber %@ hoje. Abra o Sweeply para registrar o pagamento."],
    "Your %@ from %@ should be processed today.": ["pt-BR": "Seu %@ de %@ deve ser processado hoje."],
    "Saving...": ["pt-BR": "Salvando..."],
    "Leave Team": ["pt-BR": "Sair da equipe"],
    "Leaving team…": ["pt-BR": "Saindo da equipe…"],
    "Keep holding…": ["pt-BR": "Continue segurando…"],
    "Hold to leave this team": ["pt-BR": "Segure para sair desta equipe"],
    "%@ for %@ is due in %d days — %@": ["pt-BR": "%@ para %@ vence em %d dias — %@"],
    "Wrong email or password. Please try again.": ["pt-BR": "E-mail ou senha incorretos. Tente novamente."],
    "Check your email and confirm your account first.": ["pt-BR": "Verifique seu e-mail e confirme sua conta primeiro."],
    "An account with this email already exists. Try signing in.": ["pt-BR": "Já existe uma conta com este e-mail. Tente entrar."],
    "Password must be at least 6 characters.": ["pt-BR": "A senha deve ter pelo menos 6 caracteres."],
    "No internet connection. Check your network and try again.": ["pt-BR": "Sem conexão com a internet. Verifique sua rede e tente novamente."],
    "Too many attempts. Please wait a moment and try again.": ["pt-BR": "Muitas tentativas. Aguarde um momento e tente novamente."],
    "Password reset email sent to %@.": ["pt-BR": "E-mail de redefinição de senha enviado para %@."],
    "Payment for this week...": ["pt-BR": "Pagamento desta semana..."],
    "Search clients or services...": ["pt-BR": "Buscar clientes ou serviços..."],
    "Delete Invoice?": ["pt-BR": "Excluir fatura?"],
    "Search by name or address...": ["pt-BR": "Buscar por nome ou endereço..."],
    "Their name": ["pt-BR": "Nome da pessoa"],
    "Email address": ["pt-BR": "Endereço de e-mail"],
    "e.g. Carpet Cleaning": ["pt-BR": "ex.: Limpeza de Carpete"],
    "Optional": ["pt-BR": "Opcional"],
    "Enter your email address": ["pt-BR": "Digite seu endereço de e-mail"],
    "Too short": ["pt-BR": "Muito curta"],
    "Weak": ["pt-BR": "Fraca"],
    "Good": ["pt-BR": "Boa"],
    "Strong": ["pt-BR": "Forte"],
    "you@example.com": ["pt-BR": "voce@exemplo.com"],
    "Create your service catalog — these appear\nin new job and invoice pickers.": ["pt-BR": "Crie seu catálogo de serviços — eles aparecem\nnos seletores de novo serviço e nova fatura."],
    "3 Months": ["pt-BR": "3 Meses"],
    "Does not repeat": ["pt-BR": "Não se repete"],
    "Every week": ["pt-BR": "Toda semana"],
    "Every 2 weeks": ["pt-BR": "A cada 2 semanas"],
    "Every month": ["pt-BR": "Todo mês"],
    "Supplies": ["pt-BR": "Materiais"],
    "Fuel": ["pt-BR": "Combustível"],
    "Equipment": ["pt-BR": "Equipamento"],
    "Insurance": ["pt-BR": "Seguro"],
    "Marketing": ["pt-BR": "Marketing"],
    "Other": ["pt-BR": "Outro"],
    "Owner": ["pt-BR": "Dono"],
    "Different rate per service type": ["pt-BR": "Taxa diferente por tipo de serviço"],
    "$X for all jobs done that day": ["pt-BR": "$X por todos os serviços feitos naquele dia"],
    "$X for all jobs done that week": ["pt-BR": "$X por todos os serviços feitos naquela semana"],
    "Not configured": ["pt-BR": "Não configurado"],
    "%d service rates · %@": ["pt-BR": "%d taxas de serviço · %@"],
    "%d service rates · %@%@": ["pt-BR": "%d taxas de serviço · %@%@"],
    "%@%@": ["pt-BR": "%@%@"],
    "%@ %@%@": ["pt-BR": "%@ %@%@"],
    "per day": ["pt-BR": "por dia"],
    "per week": ["pt-BR": "por semana"],
    "arrangement": ["pt-BR": "acordo"],
    "Standard Clean": ["pt-BR": "Limpeza Padrão"],
    "Deep Clean": ["pt-BR": "Limpeza Profunda"],
    "Move In/Out": ["pt-BR": "Mudança Entrada/Saída"],
    "Post Construction": ["pt-BR": "Pós-obra"],
    "Office Clean": ["pt-BR": "Limpeza de Escritório"],
    "Net %d": ["pt-BR": "%d dias"],
    "e.g. Week of Apr 21": ["pt-BR": "ex.: Semana de 21 de abr."],
    "How much?": ["pt-BR": "Quanto?"],
    "ME": ["pt-BR": "EU"],

    // MARK: - Added 2026-05-23 (missing-key audit)
    "Accept": ["pt-BR": "Aceitar"],
    "Decline": ["pt-BR": "Recusar"],
    "Members": ["pt-BR": "Membros"],
    "Invite a Cleaner": ["pt-BR": "Convidar Faxineiro"],
    "Invite sent · Tap to resend": ["pt-BR": "Convite enviado · Toque para reenviar"],
    "Add your first cleaner to start assigning jobs": ["pt-BR": "Adicione seu primeiro faxineiro para começar a atribuir serviços"],
    "Your crew starts here": ["pt-BR": "Sua equipe começa aqui"],
    "Add your first client to start booking jobs and sending invoices.": ["pt-BR": "Adicione seu primeiro cliente para começar a agendar serviços e enviar faturas."],
    "Your client roster starts here": ["pt-BR": "Sua carteira de clientes começa aqui"],
    "Avg jobs": ["pt-BR": "Média serviços"],
    "No matches": ["pt-BR": "Sem resultados"],
    "Nothing matches \"%@\". Try a different name or address.": ["pt-BR": "Nada encontrado para \"%@\". Tente um nome ou endereço diferente."],
    "City": ["pt-BR": "Cidade"],
    "State": ["pt-BR": "Estado"],
    "ZIP": ["pt-BR": "CEP"],
    "Email Address": ["pt-BR": "E-mail"],
    "Full Name": ["pt-BR": "Nome Completo"],
    "Phone Number": ["pt-BR": "Telefone"],
    "John": ["pt-BR": "João"],
    "Doe": ["pt-BR": "Silva"],
    "Miami": ["pt-BR": "São Paulo"],
    "33101": ["pt-BR": "01310-100"],
    "(555) 000-0000": ["pt-BR": "(11) 91234-5678"],
    "john@example.com": ["pt-BR": "joao@exemplo.com"],
    "No extras configured": ["pt-BR": "Nenhum extra configurado"],
    "No services configured": ["pt-BR": "Nenhum serviço configurado"],
    "Add extras like laundry, dishes, or window cleaning.": ["pt-BR": "Adicione extras como lavanderia, louça ou limpeza de janelas."],
    "Add services to speed up job and invoice creation.": ["pt-BR": "Adicione serviços para agilizar a criação de serviços e faturas."],
    "Owner enters custom amount": ["pt-BR": "Proprietário insere valor personalizado"],
    "+ EXTRA": ["pt-BR": "+ EXTRA"],
    "PRICING": ["pt-BR": "PREÇOS"],
    "RECURRENCE": ["pt-BR": "RECORRÊNCIA"],
    "SCHEDULE": ["pt-BR": "AGENDA"],
    "%d job": ["pt-BR": "%d serviço"],
    "%d jobs": ["pt-BR": "%d serviços"],
    "$3,200": ["pt-BR": "R$ 3.200"],
    "OWNER": ["pt-BR": "PROPRIETÁRIO"],
    "e.g. Sunrise Cleaning": ["pt-BR": "ex.: Limpeza Aurora"],
    "123 Main St": ["pt-BR": "Rua Principal, 123"],
    "Search states": ["pt-BR": "Buscar estados"],
    "Repeat until": ["pt-BR": "Repetir até"],
    "Overdue since %@": ["pt-BR": "Vencido desde %@"],

    // MARK: - Offline / Network
    "No internet connection": ["pt-BR": "Sem conexão com a internet"],

    // MARK: - Monthly Revenue Goal (SettingsView + DashboardView)
    "Monthly Goal": ["pt-BR": "Meta Mensal"],
    "Track your revenue against a monthly target on the Dashboard.": ["pt-BR": "Acompanhe sua receita em relação a uma meta mensal no Painel."],
    "Revenue Goal": ["pt-BR": "Meta de Receita"],
    "Set to 0 to hide the goal tracker.": ["pt-BR": "Defina como 0 para ocultar o rastreador de metas."],
    "Save Goal": ["pt-BR": "Salvar Meta"],
    "Goal reached": ["pt-BR": "Meta atingida"],

    // MARK: - About page (SettingsView)
    "Made with care for cleaning businesses.": ["pt-BR": "Feito com cuidado para empresas de limpeza."],
    ]

    static func translate(_ key: String) -> String {
        if let translated = translations[key]?["pt-BR"] {
            return translated
        }
        #if DEBUG
        Self.logMissing(key)
        #endif
        return key
    }

    /// Extracts the ordered list of format specifier types (`d`, `@`, `f`, etc.)
    /// from a printf-style template, ignoring `%%` literals and width/precision
    /// modifiers. Used to verify a translated template matches the original
    /// before passing to `String(format:)`.
    static func formatSpecifiers(in template: String) -> [Character] {
        var result: [Character] = []
        let chars = Array(template)
        var i = 0
        while i < chars.count {
            if chars[i] == "%" {
                if i + 1 < chars.count, chars[i + 1] == "%" {
                    i += 2
                    continue
                }
                var j = i + 1
                while j < chars.count, !"dDiouxXeEfgGsScCpaAlLhq@".contains(chars[j]) {
                    j += 1
                }
                if j < chars.count {
                    result.append(chars[j])
                    i = j + 1
                    continue
                }
            }
            i += 1
        }
        return result
    }

    #if DEBUG
    private static var loggedMissingKeys = Set<String>()
    private static let missingKeysQueue = DispatchQueue(label: "localization.missingKeys")

    private static func logMissing(_ key: String) {
        missingKeysQueue.sync {
            guard !loggedMissingKeys.contains(key) else { return }
            loggedMissingKeys.insert(key)
            print("[Localization] Missing pt-BR translation for: \"\(key)\"")
        }
    }

    /// Returns the set of English keys that the running app has requested but
    /// don't have a pt-BR translation. Call from a debug menu to audit coverage.
    static var missingKeys: Set<String> {
        missingKeysQueue.sync { loggedMissingKeys }
    }
    #endif
}
