import Foundation

enum Localization {
    private static let translations: [String: [String: String]] = [

    // MARK: - Common / General
    "Dashboard": ["pt-BR": "Painel"],
    "Schedule": ["pt-BR": "Agenda"],
    "Clients": ["pt-BR": "Clientes"],
    "Finances": ["pt-BR": "Financeiro"],
    "Business": ["pt-BR": "Negócio"],
    "Settings": ["pt-BR": "Configurações"],
    "Close": ["pt-BR": "Fechar"],
    "Save": ["pt-BR": "Salvar"],
    "Cancel": ["pt-BR": "Cancelar"],
    "Done": ["pt-BR": "Concluído"],
    "Delete": ["pt-BR": "Excluir"],
    "Edit": ["pt-BR": "Editar"],
    "Add": ["pt-BR": "Adicionar"],
    "View all": ["pt-BR": "Ver tudo"],
    "Loading...": ["pt-BR": "Carregando..."],
    "Error": ["pt-BR": "Erro"],
    "Success": ["pt-BR": "Sucesso"],
    "Overview": ["pt-BR": "Visão Geral"],
    "Value": ["pt-BR": "Valor"],
    "Week": ["pt-BR": "Semana"],
    "Now": ["pt-BR": "Agora"],
    "Pay": ["pt-BR": "Pagamento"],

    // MARK: - Dashboard
    "Good morning": ["pt-BR": "Bom dia"],
    "Good afternoon": ["pt-BR": "Boa tarde"],
    "Good evening": ["pt-BR": "Boa noite"],
    "Total Clients": ["pt-BR": "Total de Clientes"],
    "Upcoming Jobs": ["pt-BR": "Próximos Jobs"],
    "Revenue": ["pt-BR": "Faturamento"],
    "Outstanding": ["pt-BR": "Pendente"],
    "Completed": ["pt-BR": "Concluídos"],
    "Remaining": ["pt-BR": "Restantes"],
    "Week Earned": ["pt-BR": "Ganho na Semana"],
    "Today's Schedule": ["pt-BR": "Agenda de Hoje"],
    "No jobs scheduled for today": ["pt-BR": "Nenhum job agendado para hoje"],
    "Business Health": ["pt-BR": "Saúde do Negócio"],
    "Job Value": ["pt-BR": "Valor dos Jobs"],
    "Total value of this week's jobs": ["pt-BR": "Valor total dos jobs da semana"],
    "Visits Scheduled": ["pt-BR": "Visitas Agendadas"],
    "Outstanding Invoices": ["pt-BR": "Faturas Pendentes"],
"All caught up — no outstanding invoices": ["pt-BR": "Tudo em dia — sem faturas pendentes"],
    "Mark Paid": ["pt-BR": "Marcar Pago"],
    "Avg Job Value": ["pt-BR": "Valor Médio do Job"],
    "Weekly Jobs": ["pt-BR": "Jobs da Semana"],
    "Jobs done this week": ["pt-BR": "Jobs feitos esta semana"],
    "Earned This Month": ["pt-BR": "Ganho Este Mês"],
    "Collected All-Time": ["pt-BR": "Coletado no Total"],
    "Active This Month": ["pt-BR": "Ativo Este Mês"],
    "Upcoming jobs": ["pt-BR": "Jobs futuros"],
    "No upcoming jobs": ["pt-BR": "Nenhum job próximo"],
    "Most requested services this month": ["pt-BR": "Serviços mais pedidos este mês"],
    "Highest activity this month": ["pt-BR": "Maior atividade este mês"],
    "How the operation is moving this month": ["pt-BR": "Como a operação está este mês"],
    "Operational Overview": ["pt-BR": "Visão Operacional"],
    "Your nearest scheduled visit": ["pt-BR": "Sua próxima visita agendada"],
    "Next Up": ["pt-BR": "Próximo"],
    "Completed Jobs": ["pt-BR": "Jobs Concluídos"],
    "Services": ["pt-BR": "Serviços"],
    "Extras": ["pt-BR": "Extras"],
    "Role": ["pt-BR": "Cargo"],
    "First Name *": ["pt-BR": "Nome *"],
    "Last Name": ["pt-BR": "Sobrenome"],
    "Street Address": ["pt-BR": "Endereço"],
    "Street": ["pt-BR": "Rua"],
    "Entry Instructions": ["pt-BR": "Instruções de Acesso"],
    "Assigned": ["pt-BR": "Atribuídos"],
    "Completed": ["pt-BR": "Concluídos"],
    "Upcoming": ["pt-BR": "Próximos"],
    "Earned": ["pt-BR": "Ganho"],
    "Total": ["pt-BR": "Total"],
    "Active": ["pt-BR": "Ativo"],
    "Invited": ["pt-BR": "Convidado"],
    "Inactive": ["pt-BR": "Inativo"],
    "Jobs scheduled for the next 7 days": ["pt-BR": "Jobs agendados para os próximos 7 dias"],
    "This Month": ["pt-BR": "Este Mês"],
    "Job Started": ["pt-BR": "Job Iniciado"],
    "Job Completed": ["pt-BR": "Job Concluído"],
    "Job Cancelled": ["pt-BR": "Job Cancelado"],
    "Jobs Done": ["pt-BR": "Jobs Feitos"],
    "Revenue Milestone": ["pt-BR": "Meta de Faturamento"],
    "Revenue Milestone Reached 🎉": ["pt-BR": "Meta de Faturamento Atingida 🎉"],
    "Done Wk": ["pt-BR": "Feito Sem"],
    "In Prog.": ["pt-BR": "Em And."],
    "Mark Complete": ["pt-BR": "Marcar Concluído"],
    "View Job": ["pt-BR": "Ver Job"],
    "Revenue Milestone 🎉": ["pt-BR": "Meta de Faturamento 🎉"],
    "DAILY PAY": ["pt-BR": "PAGAMENTO DIÁRIO"],
    "It's Pay Day!": ["pt-BR": "É Dia de Pagamento!"],
    "Gross Earned": ["pt-BR": "Total Ganho"],
    "Jobs Done": ["pt-BR": "Jobs Feitos"],
    "Avg / Job": ["pt-BR": "Média / Job"],
    "Payment History": ["pt-BR": "Histórico de Pagamentos"],
    "Received payments": ["pt-BR": "Pagamentos recebidos"],
    "Avg/Job": ["pt-BR": "Média/Job"],
    "In Progress": ["pt-BR": "Em Andamento"],
    "Overdue": ["pt-BR": "Vencido"],
    "Net Profit": ["pt-BR": "Lucro Líquido"],
    "avg. invoice": ["pt-BR": "fatura média"],
    "Collection": ["pt-BR": "Cobrança"],
    "Invoices": ["pt-BR": "Faturas"],
    "Jobs": ["pt-BR": "Jobs"],
    "Scheduled": ["pt-BR": "Agendado"],
    "Coming up": ["pt-BR": "Próximos"],
    "Clear schedule": ["pt-BR": "Agenda livre"],
    "Revenue": ["pt-BR": "Faturamento"],
    "Expenses": ["pt-BR": "Despesas"],
    "Collected": ["pt-BR": "Coletado"],
    "Scheduled jobs": ["pt-BR": "Jobs agendados"],
    "Average Ticket": ["pt-BR": "Ticket Médio"],
    "Earned This Month": ["pt-BR": "Ganho Este Mês"],
    "Active This Month": ["pt-BR": "Ativo Este Mês"],
    "Total Clients": ["pt-BR": "Total de Clientes"],
    "Recurring Jobs": ["pt-BR": "Jobs Recorrentes"],
    "Value": ["pt-BR": "Valor"],
    "Duration": ["pt-BR": "Duração"],
    "EARNINGS": ["pt-BR": "GANHOS"],
    "Finance": ["pt-BR": "Financeiro"],
    "Finances": ["pt-BR": "Financeiro"],
    "Name": ["pt-BR": "Nome"],
    "Email": ["pt-BR": "E-mail"],
    "Phone": ["pt-BR": "Telefone"],
    
    // MARK: - Cleaner specific
    "Jobs scheduled for the next 7 days": ["pt-BR": "Jobs agendados para os próximos 7 dias"],
    "All Time": ["pt-BR": "Todo Período"],

    // MARK: - Settings
    "Profile": ["pt-BR": "Perfil"],
    "Preferences": ["pt-BR": "Preferências"],
    "Account": ["pt-BR": "Conta"],
    "Push Notifications": ["pt-BR": "Notificações Push"],
    "Job reminders, invoice alerts": ["pt-BR": "Lembretes de jobs, alertas de faturas"],
    "Require Face ID": ["pt-BR": "Exigir Face ID"],
    "Locks app when it goes to background": ["pt-BR": "Bloqueia app quando vai para segundo plano"],
    "Sync Jobs to Calendar": ["pt-BR": "Sincronizar Jobs com Calendário"],
    "Adds scheduled jobs to your Calendar app": ["pt-BR": "Adiciona jobs agendados ao seu aplicativo Calendário"],
    "Reset Password": ["pt-BR": "Redefinir Senha"],
    "Version": ["pt-BR": "Versão"],
    "Build": ["pt-BR": "Build"],
    "Delete Account": ["pt-BR": "Excluir Conta"],
    "Business Name": ["pt-BR": "Nome do Negócio"],
    "Business Address": ["pt-BR": "Endereço do Negócio"],
    "Job Defaults": ["pt-BR": "Padrões de Job"],
    "Default Hourly Rate": ["pt-BR": "Taxa Horária Padrão"],
    "Default Duration (hrs)": ["pt-BR": "Duração Padrão (hrs)"],
    "Manage Services": ["pt-BR": "Gerenciar Serviços"],
    "Job Extras": ["pt-BR": "Extras de Job"],
    "Reminder Timing": ["pt-BR": "Tempo do Lembrete"],
    "1 hr before": ["pt-BR": "1 hora antes"],
    "Morning of": ["pt-BR": "Manhã do dia"],
    "Day before": ["pt-BR": "Dia anterior"],
    "Send Test Notification": ["pt-BR": "Enviar Notificação de Teste"],
    "5s delay": ["pt-BR": "5s de atraso"],
    "Full name is required.": ["pt-BR": "Nome completo é obrigatório."],
    "Business name is required.": ["pt-BR": "Nome do negócio é obrigatório."],
    "Enter a valid email address.": ["pt-BR": "Digite um endereço de e-mail válido."],
    "Enter a valid email address": ["pt-BR": "Digite um endereço de e-mail válido"],
    "First name is required": ["pt-BR": "Nome é obrigatório"],
    "Settings saved.": ["pt-BR": "Configurações salvas."],
    "No authenticated session was found.": ["pt-BR": "Nenhuma sessão autenticada foi encontrada."],
    "Add your email address before requesting a password reset.": ["pt-BR": "Adicione seu endereço de e-mail antes de solicitar redefinição de senha."],
    "Password reset is not available in this mode.": ["pt-BR": "Redefinição de senha não está disponível neste modo."],
    "Password reset email sent to": ["pt-BR": "E-mail de redefinição de senha enviado para"],
    "Failed to save changes.": ["pt-BR": "Falha ao salvar alterações."],
    "Unable to save your settings right now.": ["pt-BR": "Não foi possível salvar suas configurações agora."],
    "Face ID Lock": ["pt-BR": "Bloqueio por Face ID"],
    "Require Face ID when returning to app": ["pt-BR": "Exigir Face ID ao retornar ao app"],
    "Sync to Calendar": ["pt-BR": "Sincronizar com Calendário"],
    "Managed by iOS Settings": ["pt-BR": "Gerenciado pelo iOS"],
    "LANGUAGE": ["pt-BR": "IDIOMA"],
    "SECURITY & SYNC": ["pt-BR": "SEGURANÇA E SINCRONIZAÇÃO"],
    "PERSONAL INFO": ["pt-BR": "INFORMAÇÕES PESSOAIS"],
    "BUSINESS": ["pt-BR": "NEGÓCIO"],
    "NOTIFICATIONS": ["pt-BR": "NOTIFICAÇÕES"],
    "PREFERENCES": ["pt-BR": "PREFERÊNCIAS"],
    "DANGER ZONE": ["pt-BR": "ZONA DE PERIGO"],
    "Switch to My Business": ["pt-BR": "Mudar para Meu Negócio"],
    "Cleaning Business": ["pt-BR": "Negócio de Limpeza"],
    "My Business": ["pt-BR": "Meu Negócio"],
    "Support": ["pt-BR": "Suporte"],
    "Subscription": ["pt-BR": "Assinatura"],
    "Product updates": ["pt-BR": "Novidades do Produto"],
    "Refer a friend": ["pt-BR": "Indicar um Amigo"],
    "About": ["pt-BR": "Sobre"],
    "Company details": ["pt-BR": "Dados da Empresa"],
    "Logout": ["pt-BR": "Sair"],
    "Log out": ["pt-BR": "Sair"],
    "You'll need to sign in again to access your account.": ["pt-BR": "Você precisará fazer login novamente para acessar sua conta."],
    "MY TEAMS": ["pt-BR": "MINHAS EQUIPES"],
    "Re-run App Intro": ["pt-BR": "Revisão da Introdução"],
    "Re-run Business Setup": ["pt-BR": "Revisão Configuração do Negócio"],
    "Showing on your dashboard": ["pt-BR": "Exibindo no seu painel"],
    "APP INFO": ["pt-BR": "INFORMAÇÕES DO APP"],
    "TEAM": ["pt-BR": "EQUIPE"],

    // MARK: - Language
    "Language": ["pt-BR": "Idioma"],
    "App Language": ["pt-BR": "Idioma do App"],
    "Choose your preferred language": ["pt-BR": "Escolha seu idioma preferido"],

    // MARK: - Notifications
    "Notifications": ["pt-BR": "Notificações"],
    "All": ["pt-BR": "Todas"],
    "Unread": ["pt-BR": "Não lidas"],
    "No notifications": ["pt-BR": "Sem notificações"],
    "All caught up": ["pt-BR": "Tudo em dia"],
    "No schedule updates": ["pt-BR": "Sem atualizações de agenda"],
    "No job updates": ["pt-BR": "Sem atualizações de jobs"],
    "No billing activity": ["pt-BR": "Sem atividade de faturamento"],
    "You're up to date. New notifications will appear here.": ["pt-BR": "Você está em dia. Novas notificações aparecerão aqui."],
    "You've read everything. Check back later for updates.": ["pt-BR": "Você leu tudo. Volte mais tarde para atualizações."],
    "No schedule changes or updates at the moment.": ["pt-BR": "Nenhuma mudança ou atualização de agenda no momento."],
    "No job updates at the moment.": ["pt-BR": "Nenhuma atualização de job no momento."],
    "No invoice or payment activity to show.": ["pt-BR": "Nenhuma atividade de fatura ou pagamento para mostrar."],
    "Mark read": ["pt-BR": "Marcar como lido"],
    "Mark as Unread": ["pt-BR": "Marcar como não lido"],
    "Mark as Read": ["pt-BR": "Marcar como lido"],
    "Billing": ["pt-BR": "Faturamento"],
    "No team activity": ["pt-BR": "Sem atividade da equipe"],
    "Invite acceptances and team updates will appear here.": ["pt-BR": "Aceitações de convite e atualizações da equipe aparecerão aqui."],
    "Check-ins, completions, and job assignments will appear here.": ["pt-BR": "Check-ins, conclusões e atribuições de jobs aparecerão aqui."],
    "Invoice due dates and payment confirmations will appear here.": ["pt-BR": "Datas de vencimento e confirmações de pagamento aparecerão aqui."],
    "Job in 1 Hour": ["pt-BR": "Job em 1 Hora"],
    "Standard Clean at": ["pt-BR": "Limpeza Padrão em"],
    "Invoice Due Soon": ["pt-BR": "Fatura Vencendo em Breve"],
    "is due in %d days": ["pt-BR": "vence em %d dias"],
    "Enabled — job reminders & alerts": ["pt-BR": "Ativado — lembretes de jobs e alertas"],
    "Tap to enable job reminders": ["pt-BR": "Toque para ativar lembretes de jobs"],
    "Job Reminder": ["pt-BR": "Lembrete de Job"],
    "Invoice Due": ["pt-BR": "Fatura Vencendo"],
    "Test": ["pt-BR": "Teste"],
    "Standard Clean at Sarah M. — 123 Main St": ["pt-BR": "Limpeza Padrão na Sarah M. — Rua Principal 123"],
    "INV-0042 for Sarah M. is due in 3 days — $320.00": ["pt-BR": "INV-0042 para Sarah M. vence em 3 dias — R$ 320,00"],
    "Test Notification": ["pt-BR": "Notificação de Teste"],

    // MARK: - Onboarding
    "Welcome to Sweeply": ["pt-BR": "Bem-vindo ao Sweeply"],
    "Next": ["pt-BR": "Próximo"],
    "Skip": ["pt-BR": "Pular"],
    "Get Started": ["pt-BR": "Começar"],
    "Let's set up\nyour business": ["pt-BR": "Vamos configurar\nseu negócio"],
    "This appears on your invoices and client messages.": ["pt-BR": "Isto aparece nas suas faturas e mensagens para clientes."],
    "Your name": ["pt-BR": "Seu nome"],
    "Business name (e.g. Sunrise Cleaning)": ["pt-BR": "Nome do negócio (ex: Limpeza Sunrise)"],
    "Phone (optional)": ["pt-BR": "Telefone (opcional)"],
    "What services\ndo you offer?": ["pt-BR": "Quais serviços\nvocê oferece?"],
    "Prices are fully editable anytime in Settings.": ["pt-BR": "Os preços são editáveis a qualquer momento nas Configurações."],
    "MAIN SERVICES": ["pt-BR": "SERVIÇOS PRINCIPAIS"],
    "ADD-ONS & EXTRAS": ["pt-BR": "ADICIONAIS E EXTRAS"],
    "Scheduling & job tracking": ["pt-BR": "Agendamento e controle de jobs"],
    "Invoicing & payments": ["pt-BR": "Faturamento e pagamentos"],
    "Built for cleaners": ["pt-BR": "Feito para faxineiros"],
    "Open Dashboard": ["pt-BR": "Abrir Painel"],
    "Try Again": ["pt-BR": "Tentar Novamente"],
    "Couldn't save your info — tap to try again.": ["pt-BR": "Não foi possível salvar — toque para tentar novamente."],
    "Stay on top of jobs & invoices": ["pt-BR": "Fique por dentro dos jobs e faturas"],
    "Get reminders before they're due": ["pt-BR": "Receba lembretes antes dos vencimentos"],
    "Welcome to Sweeply,": ["pt-BR": "Bem-vindo ao Sweeply,"],
    "services ready to go": ["pt-BR": "serviços prontos para uso"],
    "service ready to go": ["pt-BR": "serviço pronto para uso"],
    "is all set": ["pt-BR": "está configurado"],
    "Schedule Smarter": ["pt-BR": "Agende com Inteligência"],
    "Get Paid Faster": ["pt-BR": "Receba Mais Rápido"],
    "Scheduling": ["pt-BR": "Agendamento"],
    "Invoicing": ["pt-BR": "Faturamento"],
    "Let's get you set up": ["pt-BR": "Vamos configurar"],
    "Get your workspace ready and start managing jobs with ease.": ["pt-BR": "Prepare seu espaço de trabalho e comece a gerenciar jobs com facilidade."],
    "Build your team": ["pt-BR": "Construa sua equipe"],
    "Invite team members who'll complete jobs with you. You can always add more later.": ["pt-BR": "Convide membros da equipe que completarão jobs com você. Você sempre pode adicionar mais depois."],
    "Invite team members who'll complete jobs with you.": ["pt-BR": "Convide membros da equipe que completarão jobs com você."],
    "Fill in name and email above to add a team member.": ["pt-BR": "Preencha nome e e-mail acima para adicionar um membro da equipe."],
    "SETUP COMPLETE": ["pt-BR": "CONFIGURAÇÃO CONCLUÍDA"],
    "Your business is ready to run.": ["pt-BR": "Seu negócio está pronto para funcionar."],
    "WHAT'S READY": ["pt-BR": "O QUE ESTÁ PRONTO"],
    "Couldn't save — tap to try again.": ["pt-BR": "Não foi possível salvar — toque para tentar novamente."],
    "PENDING INVITES": ["pt-BR": "CONVITES PENDENTES"],

    // MARK: - General Actions
    "Confirm": ["pt-BR": "Confirmar"],
    "Retry": ["pt-BR": "Tentar Novamente"],
    "No results": ["pt-BR": "Sem resultados"],
    "Search": ["pt-BR": "Buscar"],
    "Back": ["pt-BR": "Voltar"],
    "Continue": ["pt-BR": "Continuar"],
    "Create": ["pt-BR": "Criar"],
    "Remove": ["pt-BR": "Remover"],
    "Apply Changes": ["pt-BR": "Aplicar Alterações"],
    "Record": ["pt-BR": "Registrar"],
    "Allow": ["pt-BR": "Permitir"],
    "Today": ["pt-BR": "Hoje"],
    "Tomorrow": ["pt-BR": "Amanhã"],
    "All Time": ["pt-BR": "Todo Período"],
    "This Week": ["pt-BR": "Esta Semana"],
    "This Month": ["pt-BR": "Este Mês"],
    "Newest First": ["pt-BR": "Mais Recentes"],
    "Oldest First": ["pt-BR": "Mais Antigos"],
    "Highest Amount": ["pt-BR": "Maior Valor"],
    "Lowest Amount": ["pt-BR": "Menor Valor"],

    // MARK: - Filters
    "Filters": ["pt-BR": "Filtros"],
    "Clear All": ["pt-BR": "Limpar Tudo"],
    "Apply": ["pt-BR": "Aplicar"],
    "Clear": ["pt-BR": "Limpar"],
    "Apply Filters": ["pt-BR": "Aplicar Filtros"],
    "All Statuses": ["pt-BR": "Todos os Status"],

    // MARK: - Auth
    "Sign In": ["pt-BR": "Entrar"],
    "Create Account": ["pt-BR": "Criar Conta"],
    "Forgot password?": ["pt-BR": "Esqueceu a senha?"],
    "Need an account? Create one": ["pt-BR": "Não tem conta? Crie uma"],
    "Already have an account? Sign in": ["pt-BR": "Já tem conta? Entre"],
    "Run your cleaning business.": ["pt-BR": "Gerencie seu negócio de limpeza."],
    "EMAIL": ["pt-BR": "E-MAIL"],
    "PASSWORD": ["pt-BR": "SENHA"],
    "At least 6 characters": ["pt-BR": "Pelo menos 6 caracteres"],
    "Check your email": ["pt-BR": "Verifique seu e-mail"],
    "We sent a reset link to": ["pt-BR": "Enviamos um link de redefinição para"],
    "Check your inbox and follow the instructions.": ["pt-BR": "Verifique sua caixa de entrada e siga as instruções."],
    "Enter your email and we'll send you a reset link.": ["pt-BR": "Digite seu e-mail e enviaremos um link de redefinição."],
    "Send Reset Link": ["pt-BR": "Enviar Link de Redefinição"],
    "Sign Out": ["pt-BR": "Sair"],
    "Signing Out...": ["pt-BR": "Saindo..."],

    // MARK: - Dashboard extended
    "REVENUE THIS WEEK": ["pt-BR": "FATURAMENTO DESTA SEMANA"],
    "No completed jobs yet this week": ["pt-BR": "Nenhum job concluído esta semana"],
    "All caught up!": ["pt-BR": "Tudo em dia!"],
    "You're all set": ["pt-BR": "Tudo certo"],
    "Every onboarding step is complete.": ["pt-BR": "Cada etapa está concluída."],
    "Finish every step before you can remove this section.": ["pt-BR": "Conclua cada etapa antes de remover esta seção."],
    "4 of 4 complete": ["pt-BR": "4 de 4 completo"],
    "Performance": ["pt-BR": "Desempenho"],
    "Swipe through your stats": ["pt-BR": "Deslize pelas estatísticas"],
    "No upcoming jobs": ["pt-BR": "Nenhum job próximo"],
    "Earnings This Week": ["pt-BR": "Ganhos desta Semana"],
    "From completed jobs this week": ["pt-BR": "De jobs concluídos esta semana"],
    "Earnings from completed jobs this month": ["pt-BR": "Ganhos de jobs concluídos este mês"],
    "Completion Rate": ["pt-BR": "Taxa de Conclusão"],
    "Share of your jobs marked complete": ["pt-BR": "Percentual de jobs marcados como concluídos"],
    "On track": ["pt-BR": "No caminho certo"],
    "Keep it up": ["pt-BR": "Continue assim"],
    "No data yet": ["pt-BR": "Sem dados ainda"],
    "Next Job": ["pt-BR": "Próximo Job"],
    "Nothing coming up": ["pt-BR": "Nada por vir"],
    "Clear schedule": ["pt-BR": "Agenda livre"],
    "No upcoming jobs scheduled": ["pt-BR": "Nenhum job agendado"],
    "Operational Overview": ["pt-BR": "Visão Operacional"],
    "Average Ticket": ["pt-BR": "Ticket Médio"],
    "Earned This Month": ["pt-BR": "Ganho Este Mês"],
"Collected All-Time": ["pt-BR": "Coletado no Total"],
    "Active This Month": ["pt-BR": "Ativo Este Mês"],
    "When new visits are scheduled, the next one will appear here.": ["pt-BR": "Quando novas visitas forem agendadas, a próxima aparecerá aqui."],
    "Scheduled Revenue": ["pt-BR": "Receita Agendada"],
    "Scheduled jobs": ["pt-BR": "Jobs agendados"],
    "No service mix yet": ["pt-BR": "Sem mix de serviços ainda"],
    "Once jobs are scheduled this month, the service split will show here.": ["pt-BR": "Quando os jobs forem agendados este mês, a divisão de serviços aparecerá aqui."],
    "No client activity yet": ["pt-BR": "Sem atividade de clientes ainda"],
    "Client rankings will update as jobs are completed.": ["pt-BR": "O ranking de clientes será atualizado conforme os jobs forem concluídos."],
"Schedule jobs to see\nservice breakdown": ["pt-BR": "Agende jobs para ver\na divisão de serviços"],
    "Jobs This Month": ["pt-BR": "Jobs Este Mês"],
"Collected": ["pt-BR": "Coletado"],
    "Avg Ticket": ["pt-BR": "Ticket Médio"],

    // MARK: - Schedule extended
    "Day": ["pt-BR": "Dia"],
    "List": ["pt-BR": "Lista"],
    "Month": ["pt-BR": "Mês"],
    "Map": ["pt-BR": "Mapa"],
    "Job Today": ["pt-BR": "Job Hoje"],
    "Jobs Today": ["pt-BR": "Jobs Hoje"],
    "Tomorrow: 1 Job": ["pt-BR": "Amanhã: 1 Job"],
    "No jobs this day": ["pt-BR": "Nenhum job neste dia"],
    "Tap + to schedule a job.": ["pt-BR": "Toque + para agendar um job."],
    "Enjoy your day off.": ["pt-BR": "Aproveite seu dia de folga."],
    "No jobs on": ["pt-BR": "Nenhum job em"],
    "Tap the date to choose another day.": ["pt-BR": "Toque na data para escolher outro dia."],
    "Nothing scheduled yet.": ["pt-BR": "Nada agendado ainda."],
    "Nothing scheduled.": ["pt-BR": "Nada agendado."],
    "Try clearing the filter.": ["pt-BR": "Tente limpar o filtro."],
    "No matching jobs": ["pt-BR": "Nenhum job encontrado"],
    "Try adjusting your filters.": ["pt-BR": "Tente ajustar seus filtros."],
    "INVOICES DUE": ["pt-BR": "FATURAS VENCENDO"],
    "Showing:": ["pt-BR": "Exibindo:"],
    "Jobs for": ["pt-BR": "Jobs de"],
    "job": ["pt-BR": "job"],
    "jobs": ["pt-BR": "jobs"],
    "done today": ["pt-BR": "feitos hoje"],
    "next job": ["pt-BR": "próximo job"],
    "updated": ["pt-BR": "atualizado"],
    "7-day rev.": ["pt-BR": "receita 7d"],
    "Busy day ahead": ["pt-BR": "Dia cheio"],
    "Starting in 1 Hour": ["pt-BR": "Começando em 1 Hora"],
    "Daily Pay": ["pt-BR": "Pagamento Diário"],
    "Weekly Pay": ["pt-BR": "Pagamento Semanal"],
    "PAYDAY — DAILY PAY": ["pt-BR": "DIA DE PAGAMENTO — DIÁRIO"],
    "PAYDAY — WEEKLY PAY": ["pt-BR": "DIA DE PAGAMENTO — SEMANAL"],
    "JOB STATUS": ["pt-BR": "STATUS DO JOB"],
    "Filter by current job progress": ["pt-BR": "Filtrar por progresso atual do job"],
    "SCHEDULE TYPE": ["pt-BR": "TIPO DE AGENDA"],
    "One-time or recurring jobs": ["pt-BR": "Jobs únicos ou recorrentes"],
    "VIEW OPTIONS": ["pt-BR": "OPÇÕES DE EXIBIÇÃO"],
    "Select which tabs appear in the schedule": ["pt-BR": "Selecione quais abas aparecem na agenda"],
    "SHOW CONTENT": ["pt-BR": "EXIBIR CONTEÚDO"],
    "Choose what appears on your schedule": ["pt-BR": "Escolha o que aparece na sua agenda"],
    "Always on": ["pt-BR": "Sempre ativo"],
    "Nothing on": ["pt-BR": "Nada em"],
    "Generate an invoice for": ["pt-BR": "Gerar uma fatura para"],
    "Are you sure you want to delete this job?": ["pt-BR": "Tem certeza que deseja excluir este job?"],
    "No photos yet. Tap \"Add Photo\" to attach images.": ["pt-BR": "Nenhuma foto ainda. Toque em \"Adicionar Foto\" para anexar imagens."],
    "Quiet week": ["pt-BR": "Semana tranquila"],

    // MARK: - Clients extended
    "Add Your First Client": ["pt-BR": "Adicione seu Primeiro Cliente"],
    "ARCHIVED": ["pt-BR": "ARQUIVADO"],
    "Archived": ["pt-BR": "Arquivado"],
    "Filter Clients": ["pt-BR": "Filtrar Clientes"],
    "STATUS": ["pt-BR": "STATUS"],
    "Show archived clients": ["pt-BR": "Mostrar clientes arquivados"],
    "SORT BY": ["pt-BR": "ORDENAR POR"],
    "Archive Client": ["pt-BR": "Arquivar Cliente"],
    "Restore Client": ["pt-BR": "Restaurar Cliente"],
    "Delete Client": ["pt-BR": "Excluir Cliente"],
    "This will permanently remove this client. This action cannot be undone.": ["pt-BR": "Isso removerá permanentemente este cliente. Esta ação não pode ser desfeita."],
    "Client deleted": ["pt-BR": "Cliente excluído"],
    "Search conversations": ["pt-BR": "Buscar conversas"],
    "Search clients": ["pt-BR": "Buscar clientes"],
    "Search invoices…": ["pt-BR": "Buscar faturas…"],
    "Start a conversation with": ["pt-BR": "Iniciar uma conversa com"],

    // MARK: - Finances
    "Advanced Finance": ["pt-BR": "Finanças Avançadas"],
    "P&L reports, cash-flow forecasting, and team payroll are available on Pro.": ["pt-BR": "Relatórios P&L, previsão de fluxo de caixa e folha de pagamento estão disponíveis no Pro."],
    "Cash-Flow Forecast": ["pt-BR": "Previsão de Fluxo de Caixa"],
    "Based on scheduled jobs & invoices": ["pt-BR": "Baseado em jobs agendados e faturas"],
    "projected over ": ["pt-BR": "projetado em "],
    " weeks · avg ": ["pt-BR": " semanas · média "],
    "/wk": ["pt-BR": "/semana"],
    "week of ": ["pt-BR": "semana de "],
    "Schedule jobs or send invoices to see your forecast.": ["pt-BR": "Agende jobs ou envie faturas para ver sua previsão."],
    "Gross Earned": ["pt-BR": "Total Ganho"],
    "Jobs Done": ["pt-BR": "Jobs Feitos"],
    "Avg / Job": ["pt-BR": "Média / Job"],
    "Completed Jobs": ["pt-BR": "Jobs Concluídos"],
    "Upcoming Earnings": ["pt-BR": "Ganhos Futuros"],
    "Scheduled jobs": ["pt-BR": "Jobs agendados"],
    "From completed jobs today": ["pt-BR": "De jobs concluídos hoje"],
    "Total jobs you've completed": ["pt-BR": "Total de jobs que você concluiu"],
    "Great work!": ["pt-BR": "Ótimo trabalho!"],
    "No jobs today": ["pt-BR": "Nenhum job hoje"],
    "jobs done this month": ["pt-BR": "jobs feitos este mês"],
    "Potential": ["pt-BR": "Potencial"],
    "Total": ["pt-BR": "Total"],
    "EARNINGS": ["pt-BR": "GANHOS"],
    "Finance": ["pt-BR": "Financeiro"],
    "No completed jobs yet": ["pt-BR": "Nenhum job concluído ainda"],
    "No completed jobs this period": ["pt-BR": "Nenhum job concluído neste período"],
    "Payment Amount": ["pt-BR": "Valor do Pagamento"],
    "Profit & Expenses": ["pt-BR": "Lucro e Despesas"],
    "Collected vs outstanding": ["pt-BR": "Recebido vs pendente"],
    "Revenue Overview": ["pt-BR": "Visão de Faturamento"],
    "Team Payroll": ["pt-BR": "Folha de Pagamento"],
    "No team members yet": ["pt-BR": "Nenhum membro da equipe ainda"],
    "Rate not set": ["pt-BR": "Taxa não definida"],
    "this period": ["pt-BR": "neste período"],
    "Your Pay Rate": ["pt-BR": "Sua Taxa de Pagamento"],
    "Net Profit": ["pt-BR": "Lucro Líquido"],
    "Avg. invoice": ["pt-BR": "Fatura média"],
"Collection": ["pt-BR": "Cobrança"],
    "Upcoming jobs value": ["pt-BR": "Valor dos jobs futuros"],
    "No expenses in": ["pt-BR": "Sem despesas em"],

    // MARK: - Job Detail / Cleaner
    "Job Details": ["pt-BR": "Detalhes do Job"],
    "Navigate to Job": ["pt-BR": "Navegar até o Job"],
    "Check In — I'm Here": ["pt-BR": "Check-in — Cheguei"],
    "Job Completed": ["pt-BR": "Job Concluído"],
    "Job Check-In": ["pt-BR": "Check-in do Job"],
    "ADDRESS": ["pt-BR": "ENDEREÇO"],
    "DURATION": ["pt-BR": "DURAÇÃO"],
    "PAY": ["pt-BR": "PAGAMENTO"],
    "hour": ["pt-BR": "hora"],
    "hours": ["pt-BR": "horas"],
"Job not found": ["pt-BR": "Job não encontrado"],
    "Today's Earnings": ["pt-BR": "Ganhos de Hoje"],
    "Done Wk": ["pt-BR": "Feito Sem"],
    "In Prog.": ["pt-BR": "Em And."],
    "Upcoming": ["pt-BR": "Próximos"],
    "From": ["pt-BR": "De"],

    // MARK: - Form Fields
    "First Name *": ["pt-BR": "Nome *"],
    "Last Name": ["pt-BR": "Sobrenome"],
    "Street Address": ["pt-BR": "Logradouro"],
"Street": ["pt-BR": "Rua"],

    // MARK: - Conversations
    "New Message": ["pt-BR": "Nova Mensagem"],

    // MARK: - Sweeply Pro
    "Sweeply Pro": ["pt-BR": "Sweeply Pro"],
    "Run your cleaning business like a pro.": ["pt-BR": "Gerencie seu negócio de limpeza como um profissional."],
    "Popular": ["pt-BR": "Popular"],
    "PRO": ["pt-BR": "PRO"],
    "MOST POPULAR": ["pt-BR": "MAIS POPULAR"],
    "Get Pro": ["pt-BR": "Adquirir Pro"],
    "STANDARD": ["pt-BR": "PADRÃO"],
    "Get Standard": ["pt-BR": "Adquirir Padrão"],
    "Restore Purchases": ["pt-BR": "Restaurar Compras"],
    "Cancel anytime · Auto-renews · Prices in USD": ["pt-BR": "Cancele a qualquer momento · Renovação automática · Preços em USD"],
    "Upgrade to Pro to unlock this feature.": ["pt-BR": "Atualize para Pro para desbloquear este recurso."],
    "See Plans": ["pt-BR": "Ver Planos"],
    "Upgrade to unlock this feature.": ["pt-BR": "Atualize para desbloquear este recurso."],
    "See Plans": ["pt-BR": "Ver Planos"],
    "Manage Subscription": ["pt-BR": "Gerenciar Assinatura"],
    "Unlock Sweeply": ["pt-BR": "Desbloquear Sweeply"],
    "Sweeply is Locked": ["pt-BR": "Sweeply Bloqueado"],
    "Your business data is protected.": ["pt-BR": "Os dados do seu negócio estão protegidos."],

    // MARK: - Widgets
    "NEXT JOB": ["pt-BR": "PRÓXIMO JOB"],
    "TODAY'S SCHEDULE": ["pt-BR": "AGENDA DE HOJE"],
    "All clear today": ["pt-BR": "Livre hoje"],
    "7-day revenue": ["pt-BR": "receita 7 dias"],
    "SWEEPLY": ["pt-BR": "SWEEPLY"],
    "THIS WK": ["pt-BR": "ESTA SEM"],
    "WEEK REVENUE": ["pt-BR": "FATURAMENTO SEMANAL"],
    "7-day earnings": ["pt-BR": "ganhos 7 dias"],
    "TODAY": ["pt-BR": "HOJE"],
    "JOBS TODAY": ["pt-BR": "JOBS HOJE"],
    "TODAY'S VALUE": ["pt-BR": "VALOR DE HOJE"],
    "job today": ["pt-BR": "job hoje"],
    "jobs today": ["pt-BR": "jobs hoje"],
    "None completed yet": ["pt-BR": "Nenhum concluído ainda"],

    // MARK: - Schedule
    "Choose Date": ["pt-BR": "Escolher Data"],

    // MARK: - Quick Actions
    "Go Back": ["pt-BR": "Voltar"],
"Job Files": ["pt-BR": "Arquivos do Job"],
    "Job Description": ["pt-BR": "Descrição do Job"],
    ]

    static func translate(_ key: String) -> String {
        return translations[key]?["pt-BR"] ?? key
    }
}
