import Foundation

enum Localization {
    private static let translations: [String: [String: String]] = [
    
    // MARK: - Common / General
    "Dashboard": ["pt-BR": "Painel"],
    "Schedule": ["pt-BR": "Agenda"],
    "Clients": ["pt-BR": "Clientes"],
    "Finances": ["pt-BR": "Financeiro"],
    "Business": ["pt-BR": "Negócio"],
    "Settings": ["pt-BR": "Configurações"],
    "Close": ["pt-BR": "Fechar"],
    "Save": ["pt-BR": "Salvar"],
    "Cancel": ["pt-BR": "Cancelar"],
    "Done": ["pt-BR": "Concluído"],
    "Delete": ["pt-BR": "Excluir"],
    "Edit": ["pt-BR": "Editar"],
    "Add": ["pt-BR": "Adicionar"],
    "View all": ["pt-BR": "Ver tudo"],
    "Loading...": ["pt-BR": "Carregando..."],
    "Error": ["pt-BR": "Erro"],
    "Success": ["pt-BR": "Sucesso"],
    
    // MARK: - Dashboard
    "Good morning": ["pt-BR": "Bom dia"],
    "Good afternoon": ["pt-BR": "Boa tarde"],
    "Good evening": ["pt-BR": "Boa noite"],
    "Total Clients": ["pt-BR": "Total de Clientes"],
    "Upcoming Jobs": ["pt-BR": "Próximos Jobs"],
    "Revenue": ["pt-BR": "Faturamento"],
    "Outstanding": ["pt-BR": "Pendente"],
    "This Week": ["pt-BR": "Esta Semana"],
    "Completed": ["pt-BR": "Concluídos"],
    "Remaining": ["pt-BR": "Restantes"],
    "Week Earned": ["pt-BR": "Ganho na Semana"],
    "Today's Schedule": ["pt-BR": "Agenda de Hoje"],
    "No jobs scheduled for today": ["pt-BR": "Nenhum job agendado para hoje"],
    "Business Health": ["pt-BR": "Saúde do Negócio"],
    "Job Value": ["pt-BR": "Valor dos Jobs"],
    "Total value of this week's jobs": ["pt-BR": "Valor total dos jobs da semana"],
    "Visits Scheduled": ["pt-BR": "Visitas Agendadas"],
    "Outstanding Invoices": ["pt-BR": "Faturas Pendentes"],
    "All caught up — no outstanding invoices": ["pt-BR": "Tudo em dia — sem faturas pendentes"],
    "Mark Paid": ["pt-BR": "Marcar Pago"],
    
    // MARK: - Getting Started
    "Get started": ["pt-BR": "Começar"],
    "Add your first client": ["pt-BR": "Adicione seu primeiro cliente"],
    "Schedule your first job": ["pt-BR": "Agende seu primeiro job"],
    "Create your first invoice": ["pt-BR": "Crie sua primeira fatura"],
    "Set up your business profile": ["pt-BR": "Configure seu perfil empresarial"],
    "of 4 complete": ["pt-BR": "de 4 completo"],
    
    // MARK: - Clients
    "New Client": ["pt-BR": "Novo Cliente"],
    "Client": ["pt-BR": "Cliente"],
    "Name": ["pt-BR": "Nome"],
    "Email": ["pt-BR": "E-mail"],
    "Phone": ["pt-BR": "Telefone"],
    "Address": ["pt-BR": "Endereço"],
    "City": ["pt-BR": "Cidade"],
    "State": ["pt-BR": "Estado"],
    "ZIP": ["pt-BR": "CEP"],
    "Notes": ["pt-BR": "Notas"],
    "No clients yet": ["pt-BR": "Nenhum cliente ainda"],
    "Add your first client to get started": ["pt-BR": "Adicione seu primeiro cliente para começar"],
    "Active": ["pt-BR": "Ativo"],
    "Inactive": ["pt-BR": "Inativo"],
    "Full Name": ["pt-BR": "Nome Completo"],
    "Email Address": ["pt-BR": "Endereço de E-mail"],
    "Phone Number": ["pt-BR": "Número de Telefone"],
    
    // MARK: - Jobs
    "New Job": ["pt-BR": "Novo Job"],
    "Job": ["pt-BR": "Job"],
    "Jobs": ["pt-BR": "Jobs"],
    "Service": ["pt-BR": "Serviço"],
    "Date": ["pt-BR": "Data"],
    "Duration": ["pt-BR": "Duração"],
    "Price": ["pt-BR": "Preço"],
    "Status": ["pt-BR": "Status"],
    "Scheduled": ["pt-BR": "Agendado"],
    "In Progress": ["pt-BR": "Em Andamento"],
    "Cancelled": ["pt-BR": "Cancelado"],
    "Start Job": ["pt-BR": "Iniciar Job"],
    "Mark Complete": ["pt-BR": "Marcar Concluído"],
    "Cancel Job": ["pt-BR": "Cancelar Job"],
    "No jobs yet": ["pt-BR": "Nenhum job ainda"],
    "No jobs for this day": ["pt-BR": "Nenhum job para este dia"],
    "Select Client": ["pt-BR": "Selecionar Cliente"],
    "Select Service": ["pt-BR": "Selecionar Serviço"],
    "Select Date": ["pt-BR": "Selecionar Data"],
    "Start Time": ["pt-BR": "Horário de Início"],
    "Recurring": ["pt-BR": "Recorrente"],
    
    // MARK: - Invoices
    "New Invoice": ["pt-BR": "Nova Fatura"],
    "Invoice": ["pt-BR": "Fatura"],
    "Invoices": ["pt-BR": "Faturas"],
    "Invoice No.": ["pt-BR": "Nº da Fatura"],
    "Due Date": ["pt-BR": "Data de Vencimento"],
    "Paid": ["pt-BR": "Pago"],
    "Unpaid": ["pt-BR": "Pendente"],
    "Overdue": ["pt-BR": "Vencido"],
    "Subtotal": ["pt-BR": "Subtotal"],
    "TOTAL": ["pt-BR": "TOTAL"],
    "No invoices yet": ["pt-BR": "Nenhuma fatura ainda"],
    "Add your first service": ["pt-BR": "Adicione seu primeiro serviço"],
    "Add another service": ["pt-BR": "Adicionar outro serviço"],
    "Notes (optional)": ["pt-BR": "Notas (opcional)"],
    "Bill to": ["pt-BR": "Cobrar de"],
    "Select client": ["pt-BR": "Selecionar cliente"],
    
    // MARK: - Services
    "Service Type": ["pt-BR": "Tipo de Serviço"],
    "Standard Clean": ["pt-BR": "Limpeza Padrão"],
    "Deep Clean": ["pt-BR": "Limpeza Profunda"],
    "Move-in Clean": ["pt-BR": "Limpeza de Mudança"],
    "Move-out Clean": ["pt-BR": "Limpeza de Saída"],
    "Post-Construction": ["pt-BR": "Pós-Obra"],
    
    // MARK: - Expenses
    "Expenses": ["pt-BR": "Despesas"],
    "New Expense": ["pt-BR": "Nova Despesa"],
    "Description": ["pt-BR": "Descrição"],
    "Amount": ["pt-BR": "Valor"],
    "Category": ["pt-BR": "Categoria"],
    
    // MARK: - Team
    "Team": ["pt-BR": "Equipe"],
    "Invite Member": ["pt-BR": "Convidar Membro"],
    "Owner": ["pt-BR": "Proprietário"],
    "Cleaner": ["pt-BR": "Limpeza"],
    
    // MARK: - Settings
    "Profile": ["pt-BR": "Perfil"],
    "Preferences": ["pt-BR": "Preferências"],
    "Account": ["pt-BR": "Conta"],
    "Push Notifications": ["pt-BR": "Notificações Push"],
    "Job reminders, invoice alerts": ["pt-BR": "Lembretes de jobs, alertas de faturas"],
    "Require Face ID": ["pt-BR": "Exigir Face ID"],
    "Locks app when it goes to background": ["pt-BR": "Bloqueia app quando vai para segundo plano"],
    "Sync Jobs to Calendar": ["pt-BR": "Sincronizar Jobs com Calendário"],
    "Adds scheduled jobs to your Calendar app": ["pt-BR": "Adiciona jobs agendados ao seu aplicativo Calendário"],
    "Reset Password": ["pt-BR": "Redefinir Senha"],
    "Version": ["pt-BR": "Versão"],
    "Build": ["pt-BR": "Build"],
    "Delete Account": ["pt-BR": "Excluir Conta"],
    "Business Name": ["pt-BR": "Nome do Negócio"],
    "Business Address": ["pt-BR": "Endereço do Negócio"],
    "Job Defaults": ["pt-BR": "Padrões de Job"],
    "Default Hourly Rate": ["pt-BR": "Taxa Horária Padrão"],
    "Default Duration (hrs)": ["pt-BR": "Duração Padrão (hrs)"],
    "Manage Services": ["pt-BR": "Gerenciar Serviços"],
    "Job Extras": ["pt-BR": "Extras de Job"],
    "Reminder Timing": ["pt-BR": "Tempo do Lembrete"],
    "1 hr before": ["pt-BR": "1 hora antes"],
    "Morning of": ["pt-BR": "Manhã do dia"],
    "Day before": ["pt-BR": "Dia anterior"],
    "Send Test Notification": ["pt-BR": "Enviar Notificação de Teste"],
    "5s delay": ["pt-BR": "5s de atraso"],
    "Full name is required.": ["pt-BR": "Nome completo é obrigatório."],
    "Business name is required.": ["pt-BR": "Nome do negócio é obrigatório."],
    "Enter a valid email address.": ["pt-BR": "Digite um endereço de e-mail válido."],
    "Settings saved.": ["pt-BR": "Configurações salvas."],
    "No authenticated session was found.": ["pt-BR": "Nenhuma sessão autenticada foi encontrada."],
    "Add your email address before requesting a password reset.": ["pt-BR": "Adicione seu endereço de e-mail antes de solicitar redefinição de senha."],
    "Password reset is not available in this mode.": ["pt-BR": "Redefinição de senha não está disponível neste modo."],
    "Password reset email sent to": ["pt-BR": "E-mail de redefinição de senha enviado para"],
    
    // MARK: - Language
    "Language": ["pt-BR": "Idioma"],
    "App Language": ["pt-BR": "Idioma do App"],
    "Choose your preferred language": ["pt-BR": "Escolha seu idioma preferido"],
    
    // MARK: - Notifications
    "Notifications": ["pt-BR": "Notificações"],
    "All": ["pt-BR": "Todas"],
    "Unread": ["pt-BR": "Não lidas"],
    "No notifications": ["pt-BR": "Sem notificações"],
    "All caught up": ["pt-BR": "Tudo em dia"],
    "No schedule updates": ["pt-BR": "Sem atualizações de agenda"],
    "No job updates": ["pt-BR": "Sem atualizações de jobs"],
    "No billing activity": ["pt-BR": "Sem atividade de faturamento"],
    "You're up to date. New notifications will appear here.": ["pt-BR": "Você está em dia. Novas notificações aparecerão aqui."],
    "You've read everything. Check back later for updates.": ["pt-BR": "Você leu tudo. Volte mais tarde para atualizações."],
    "No schedule changes or updates at the moment.": ["pt-BR": "Nenhuma mudança ou atualização de agenda no momento."],
    "No job updates at the moment.": ["pt-BR": "Nenhuma atualização de job no momento."],
    "No invoice or payment activity to show.": ["pt-BR": "Nenhuma atividade de fatura ou pagamento para mostrar."],
    "Mark read": ["pt-BR": "Marcar como lido"],
    "Mark as Unread": ["pt-BR": "Marcar como não lido"],
    "Mark as Read": ["pt-BR": "Marcar como lido"],
    
    // MARK: - Onboarding
    "Welcome to Sweeply": ["pt-BR": "Bem-vindo ao Sweeply"],
    "Next": ["pt-BR": "Próximo"],
    "Skip": ["pt-BR": "Pular"],
    "Get Started": ["pt-BR": "Começar"],
    
    // MARK: - AI Chat
    "AI Assistant": ["pt-BR": "Assistente IA"],
    "How can I help?": ["pt-BR": "Como posso ajudar?"],
    "Ask anything about your business...": ["pt-BR": "Pergunte qualquer coisa sobre seu negócio..."],
    
    // MARK: - Filters
    "Filters": ["pt-BR": "Filtros"],
    "Clear All": ["pt-BR": "Limpar Tudo"],
    "Apply": ["pt-BR": "Aplicar"],
    
    // MARK: - General Actions
    "Confirm": ["pt-BR": "Confirmar"],
    "Retry": ["pt-BR": "Tentar Novamente"],
    "No results": ["pt-BR": "Sem resultados"],
    "Search": ["pt-BR": "Buscar"],
    ]
    
    static func translate(_ key: String) -> String {
        return translations[key]?["pt-BR"] ?? key
    }
}