schemaVersion: 1
sessionDefaultsProfiles:
  sweently:
    scheme: SWEEPLY
  ios:
    projectPath: /Users/joaoleite/Desktop/SWEEPLYIOSAPP/SWEEPLY/SWEEPLY.xcodeproj
    scheme: SWEEPLY
    simulatorName: iPhone 17
    simulatorId: 935F8B93-4ECB-4077-A820-2CC24A75868D
    simulatorPlatform: iOS Simulator
  sweepltest:
    projectPath: /Users/joaoleite/Desktop/SWEEPLYIOSAPP/SWEEPLY/SWEEPLY.xcodeproj
    scheme: SWEEPLY
    simulatorName: iPhone 17
    simulatorPlatform: iOS Simulator
    bundleId: com.sweeply.app
    simulatorId: 935F8B93-4ECB-4077-A820-2CC24A75868D
activeSessionDefaultsProfile: sweepltest
